### ISSUE TITLE
Terminar de cargar los datos en BBDD

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#13]

**Comment by fransaiz95** [comment]
Buenas Alvar.
Tengo las siguientes dudas para terminar con la carga de los datos:

- La pestaña del excel de temp: Donde tengo que meter esos datos? Entiendo que en la tabla rangemeteos pero no se con qué criterio
- Los campos (de la misma tabla: "rangemeteos":) wind y hum? De donde los saco?
- En la tabla: rangerenowables: Los campos start y end? Al poner el start como parte de la PK, no puedo dejarlo vacío.

**Comment by alvarag** [comment]
La tabla de datos meteorológicos creo que de momento la podemos dejar vacía, puesto que faltan datos como bien dices. Le preguntaré a ver si tiene algo actualizado.

En cuanto a rangerenowables, si no recuerdo mal ahora lo tenemos por días, ¿no? Si es así, puedes poner el campo start como las 00:00 del día y fin a las 23:59

**Comment by fransaiz95** [comment]
Okey, miraré bien lo de las horas.
No me he percatado de eso. Estaban las horas para la tabla de las demandas.
Gracias y si tienes noticias me dices.

El 26 oct. 2018 8:23, Álvar Arnaiz-González <notifications@github.com> escribió:

La tabla de datos meteorológicos creo que de momento la podemos dejar vacía, puesto que faltan datos como bien dices. Le preguntaré a ver si tiene algo actualizado.

En cuanto a rangerenowables, si no recuerdo mal ahora lo tenemos por días, ¿no? Si es así, puedes poner el campo start como las 00:00 del día y fin a las 23:59
