### ISSUE TITLE
Muestra de la app en el servidor

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#15]

**Comment by fransaiz95** [comment]
Buenas noches.

Os dejo el link a la página donde podeis ir viendo la estructura de la aplicación: [weblectric](http://server5bb4ed75b269a.servidoresdedicados.com/)

Actualmente están cargados los datos que nos proporcionaron, a la espera de que los completen para poder alimentar con datos todas nuestras tablas.
Estoy preparando las administraciones para las 4 tablas principales. Se ve en la pantalla principal de la aplicación.
Poco a poco irá cogiendo forma.

Un saludo.

**Comment by alvarag** [comment]
¡Ya va cogiendo forma! Eso está bien, puesto que nos quedan como quien dice dos meses (nos hemos comido ya la mitad del cuatrimestre) y todavía queda mucha memoria y aplicación por hacer.
Se lo voy a enviar al investigador de méxico para que lo vaya chequeando.
Gracias

**Comment by fransaiz95** [comment]
Genial. Envíaselo y nos dicen con lo que comente.

Si tiene algún mockup o idea de como le gustaría que fuese la aplicación pues sigo sus patrones.
Y si tiene necesidad de algún módulo o apartado concreto pues que lo manifieste y así cumplimos sus necesidades.

Un saludo!

**Comment by fransaiz95** [comment]
Buenas noches. 
He hecho una subida al servidor con lo que sería una administración casi completa de todo lo relacionado con las regiones. [weblectric](http://server5bb4ed75b269a.servidoresdedicados.com/)
Echadlo un ojo y me decís. Se puede ver la estructura de lo que sería la parte de la administración de los datos.
Para comentar sugerencias de flujos/maquetación y demás. 
No se si la guía de estilos es adecuada o el gris da lugar a confusión... 

Un saludo, me decis con lo que sea.

**Comment by jmaudes** [comment]
Asi sin ser un experto en el tema, cosas que me llaman la atencion:

1) Si las regiones no guardan ningun orden ... ¿como podria acceder, por ejemplo, a Acapulco, sin tener que revisar todas las paginas?

2) El boton del ojito en las regiones me lleva a las tecnologias, ¿no deberian salir por algun orden? por ejemplo, por potencia y capacidad descendentemente.

En estas 2 observaciones va implicita la posibilidad de ordenar por columnas que hay en muchas aplicaciones. Por ejemplo que en la cabecera de las tecnologies haya unos botoncitos a modoe de triangulitos que si estan activados/hundidos significa que los datos estan ordenados por esa columna

3) Cuando voy desde la region a Arcs, la tabla que muestra esta bien, pero habria que ir pensando en alguna forma de visualizar los arcos en un mapa. Si bien esto no es prioritario, siempre hemos visto que era la forma de que el proyecto tuviera mejor nota

4) Habria que valorar si meter otro pais a modo de prueba, porque en los desplegables para elegir pais queda muy soso que solo salga Mexico. De hecho cuando vamos a Regions, tengo la impresion de que estan saliendo las de todos los paises, pero pasa inadvertido porque solo tenemos uno.
Esto es: en regiones deberiamos de tener un filtro por pais, o bien en algun punto de la pantalla principal, o en Countries, seleccionar el pais, y que a partir de ese momento los datos que se administren sean solo los relativos a ese pais

Lo mismo alguna de estas cosas no es viable o logica, valoradlo
Saludos

Jesus








El vie., 9 nov. 2018 a las 0:01, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Buenas noches.
He hecho una subida al servidor con lo que sería una administración casi completa de todo lo relacionado con las regiones.
Echadlo un ojo y me decís. Se puede ver la estructura de lo que sería la parte de la administración de los datos.
Para comentar sugerencias de flujos/maquetación y demás.
No se si la guía de estilos es adecuada o el gris da lugar a confusión...

Un saludo, me decis con lo que sea.

**Comment by fransaiz95** [comment]
Efectivamente Jesús. 

Esas cosas las tenía en mente. Ayer era tarde y se me pasó dejarlo escrito:

1). En todas las pantallas donde hay tablas paginadas habrá un buscador. Así se solucionarán varios problemas que has dicho. 
Las regiones están ordenadas alfabéticamente y efectívamente aparecen todas las regiones, cuando haya filtro y se pueda buscar por nombre o país, la tabla obtendrá paginados solo esos resultados.

2).  El botón del ojito en la tabla de las regiones, no es que te lleve a las technologias.
Te lleva a la administración de los datos asociados a esa región. En el submenú de arriba te aparece el icono de tecnologías(marcado por defecto) y de arcs, pero son solo las tecnologías y arcos asociadas a esa región. Lo que estas editando y visualizando desde ahí son las tablas regions_technologies y arcs. En esta última, aquellos resultados en los que el nodo origen es la región que has seleccionado al principio.

Lo que decías de ordenar los resultados (los triangulitos de la cabecera de la tabla) también está pendiente. Tuve problemas ayer a la hora de mostrar los resultados por lo que quité la funcionalidad, pero es la idea si.

3). En cuanto a esto, estoy de acuerdo si, y está en mente tambien. Es el objetivo vaya, pero quería primero hacer lo que es toda la administración para que el pueda editar los datos y cargarlos y luego ponerme con los detalles de visualización. Pero lo que considereis vosotros. Me vais marcando.

4). Me parece bien. Podemos crear un nuevo país para que tenga más salsa la app. Me guardo un backup de la BBDD para no pisar esos datos.

Vamos comentando este tipo de cosillas que me hace bien. 
Así vamos puliendo los flujos. Muchas gracias!!

Un saludo.

**Comment by fransaiz95** [comment]
Buenas noches. 

He hecho otra subida al servidor con gran parte de la administración por medio de formularios.
Por si teneis un rato para ver los flujos y demás.
Cualquier cosa o posible pega/mejora me vais comentando.

Un saludo.

**Comment by alvarag** [comment]
Gracias, como recomendación haz un poco más "atractivo" el README.md del repositorio y pones ahí el enlace a la web (para que esté más accesible).
Se lo voy a pasar al investigador de México para que vaya chequeando

**Comment by fransaiz95** [comment]
Okey, gracias Alvar. Lo tendré en cuenta

El 15 nov. 2018 9:18, Álvar Arnaiz-González <notifications@github.com> escribió:

Gracias, como recomendación haz un poco más "atractivo" el README.md del repositorio y pones ahí el enlace a la web (para que esté más accesible).
Se lo voy a pasar al investigador de México para que vaya chequeando

**Comment by alvarag** [comment]
En la memoria de este proyecto, puedes ver las alternativas que él prueba y qué decisión toma:
https://github.com/IvanArjona/TFG-Datos-publicos/tree/master/docs
