### ISSUE TITLE
Carga de datos producción/demanda

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#16]
He hablado con Rodrigo (el cliente), algo me ha solucionado pero esta liado esta semana:

- Datos de demanda y meteorológicos mediante csv. Así que ponemos un botón para cargar csv, se sube al servidor y que lo parsee.
- Estructura: cuatro primeras columnas para el timestamp (año, mes, día, hora) y, a partir de ahí, en cada columna una región.

Esto permite que puedas usar la misma estructura para los datos de demanda y los meteorológicos.

**Comment by fransaiz95** [comment]
Okey, perfecto. 
Gracias Alvar.

**Comment by fransaiz95** [comment]
Buenas noches.

He subido al servidor lo que sería la administración de todas las tablas a expensas de terminar la carga de las tablas $rangedemand, $rangemeteo y $rangerenewable. 

Como dijimos, estas ultimas se cargan a través de la subida de un excel.
He estado probando y claro, son muchísimas filas (200.000 y pico) y me da error de que se queda sin memoria al procesar aun poniendole la opción de que coja toda la que necesite.
No se si eso se solucionaria leyendo de un csv en vez de un excel.

No obstante, con la tabla $rangedemands, podría valernos la estructura que nos dijo rodrigo en su día pues solo tiene el campo "demand". 
"Cuatro primeras columnas para el timestamp (año, mes, día, hora) y, a partir de ahí, en cada columna una región." 
Pero el resto de tablas, tienen más datos. No me termino de imaginar como sería la estructura de ese excel. 

Hay que darlo una vuelta.

Dejo deshabilitados los botones del panel. Dejo solo habilitado el de las rangedemand que es el que tiene funcionalidad.

Un saludo.

**Comment by fransaiz95** [comment]
Ahora mismo no existe ninguna validación para el fichero que hemos subido por lo que si subimos otra cosa, se lo tragará y dará error.

La lógica que habia seguido es la de borrar todos los datos de la tabla cada vez que se sube un excel pues suponía que siempre se sube con todos los datos. Ellos los obtendrán de alguna API o algo.

Otra propuesta podría ser: Hacer la carga desde las regiones. Por cada region, subir un excel/csv correspondiente. Asi nos quitaríamos el problema de la memoria pero... tendríamos que hacer la carga para cada región.

Lo valoramos.

**Comment by fransaiz95** [comment]
Me he dado cuenta de que en el servidor no se recoge bien el archivo. Algo debe de faltar de instalar bien. Se ve que el plugin no lo ha pillado del todo bien.
Pero bueno, un poco la idea general es esa.

**Comment by alvarag** [comment]
> Como dijimos, estas ultimas se cargan a través de la subida de un excel.
> He estado probando y claro, son muchísimas filas (200.000 y pico) y me da error de que se queda sin memoria al procesar aun poniendole la opción de que coja toda la que necesite.
> No se si eso se solucionaria leyendo de un csv en vez de un excel.

¿Te da error en tu propia máquina o solamente cuando lo subes al servidor?

En cuanto a lo de borrar la tabla... yo creo que es mejor que mantenga lo que hay. De este modo se podría ir subiendo por "años" y tiene más sentido que si ya tenemos la tabla hasta este año, solo haría falta meter el nuevo.

**Comment by fransaiz95** [comment]
>¿Te da error en tu propia máquina o solamente cuando lo subes al servidor?

Me da error en mi propia máquina. Cosa que me extraña porque... Cuando hice la carga inicial, leyendo directamente del fichero que estaba en disco, lo hizo sin problema. Y el número de registros era el mismo. Se ve que al no tener el fichero en disco, le cuesta más.

>En cuanto a lo de borrar la tabla... yo creo que es mejor que mantenga lo que hay. De este modo se podría ir subiendo por "años" y tiene más sentido que si ya tenemos la tabla hasta este año, solo haría falta meter el nuevo.

Vale, me parece bien. Entonces habría que ir comprobando cada registro si es el mismo o hay que editarlo verdad? 
Yo decía lo de borrar todo, para evitarnos más complejidad cada vez que leemos un dato.
Pero podemos mirar o buscar alternativas si.

**Comment by alvarag** [comment]
Sí, puedes insertar todos e ignorar los duplicates o vas comprobando uno a uno. Jesús tendrá clara cuál es la opción más recomendable en este tipo de casos.

¿Vamos a tener reunión mañana? ¿O te dedicas este siguiente sprint a documentación? Como hablamos el otro jueves.

**Comment by jmaudes** [comment]
Lo que se hace normalmente es desactivar las restricciones (PKs, FKs, ...) durante la carga, y una vez esta cargado todo se reactivan las restricciones. El tiempo de reconstruir los indices una sola vez es mucho menor que el de ir manteniendolos por cada fila que insertemos cuando se trata de miles de filas.

Esta discusion es interesante:
https://stackoverflow.com/questions/8210608/mysql-disable-enable-keys
Probrablemente tu indice sea del tipo InnoDB, pero habría que comprobarlo

Otra opcion es que hagas tus propias medidas de tiempos con las diferentes opciones que haya, y lo añadas como una aportación del proyecto

**Comment by jmaudes** [comment]
Otras 2 referencias interesantes, dependiendo del tipo de indice que tengas:

https://dev.mysql.com/doc/refman/8.0/en/optimizing-innodb-bulk-data-loading.html
https://dev.mysql.com/doc/refman/8.0/en/optimizing-myisam-bulk-data-loading.html

No me lo he leido, pero habria que tener en cuenta tambien que la transaccion no te genere un tablespace undo giganteso => por ahi podrían estar los problemas de que te de error al cargar si el tablespace es insuficiente y además de tamaño fijo. No se ... mySQL no es my SGBD normalmente

Vete estudiandotelo y nos vas contando

Jesus

**Comment by fransaiz95** [comment]
>¿Vamos a tener reunión mañana? ¿O te dedicas este siguiente sprint a documentación? Como hablamos el otro jueves.

Me dedico a terminar estas cosillas que vamos comentando y le doy caña a la documentación. Me parece bien.

En cuanto a lo que comentaba Jesús, me voy mirando los hilos si.

Otro problema que he detectado es:
Yo en local, he tenido que cambiar la configuración del archivo `php.ini` para que me dejase subir archivos de más de 2MB. 
En el servidor yo no tengo acceso a tocar esos archivos. Que solución tiene, tengo que contactar con el soporte técnico?

**Comment by fransaiz95** [comment]
Buenas Jesús, he estado mirando los enlaces que me has pasado y no he encontrado remedio.
He probado con: 
- Deshabilitar las keys y luego ponerlas
- Bloquear la tabla y desbloquearla al final: `LOCK TABLES rangedemands WRITE;`
- Deshabilitar el autocommit para las tablas InnoDB. 
- Establecer la primary key de la tabla como auto_increment para evitarme ese campo.

No he conseguido el resultado...

**Comment by jmaudes** [comment]
Supongo "No he conseguido el resultado..." es que te sigue dando error

Son semanas malas con muchas cosas que corregir, tendria que hacerme la misma instalacion de mySQL que tienes tu para investigarlo
(supongo no tienes una MV o similar para probarlo ...)

De momento, mandame al mail
-- los scripts que has probado con los pantallazos/mensajes de error
-- el csv que interviene en el problema
-- un script que cree las tablas y la llene con los datos que hay antes de cargar los datos
-- la version de mySQL usada por si tengo que instalarmela
Si no lo veo a primera vista, intento reproducir el problema a ratos
