### ISSUE TITLE
Pruebas del sistema: alta combustible y alta región

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#17]
He creado un combustible, y luego en el visor no aparece el nombre:

![imagen](https://user-images.githubusercontent.com/9881614/48539615-02004a00-e8b8-11e8-9c20-c67db9e89fea.png)

![imagen](https://user-images.githubusercontent.com/9881614/48539634-0d537580-e8b8-11e8-9041-477cc6cf9cfe.png)

**Comment by alvarag** [comment]
Otro ejemplo al crear una región para un nuevo país (Portugal en este caso):

![imagen](https://user-images.githubusercontent.com/9881614/48539766-68856800-e8b8-11e8-9b72-da869b00361b.png)

Y luego los importes han cambiado: siempre pone el máximo.

![imagen](https://user-images.githubusercontent.com/9881614/48539791-7cc96500-e8b8-11e8-8097-fc2f51dcd029.png)

**Comment by alvarag** [comment]
En tecnología, falta un campo en el formulario de consulta.

Ejemplo de alta:

![imagen](https://user-images.githubusercontent.com/9881614/48539912-de89cf00-e8b8-11e8-9d93-3a18527f86c3.png)

En la visualización falta el campo "Gen Cos":

![imagen](https://user-images.githubusercontent.com/9881614/48539984-1abd2f80-e8b9-11e8-9c7a-c6d35a5763e8.png)

**Comment by fransaiz95** [comment]
Corregido tambien lo del nombre del fuel. Despiste tonto...

En cuanto a que siempre pone lo máximo, acabo de ver por qué es. Te cuento y vemos que hacemos. Supongo que pasará en más sitios.

Cuando se especificó la BBDD, se estableció el campo 'dem_for' y 'ren_for' como un DECIMAL 7,4, que significa en MySql un decimal de longitud 7, de los cuales, 4 cifras por detrás de la coma.
Por tanto, todo número que metamos de mas de 3 cifras va a tener esta casuística. En cambio, si metemos un número de mas de 4 cifras decimales, cake ya lo valida:

![imagen](https://user-images.githubusercontent.com/33490785/48575161-816e3780-e911-11e8-9684-db1cc043cb6e.png)

Que hacemos con el otro caso? Validamos que no se pueda meter un número de más de 3 cifras "enteras"? Entiendo que meterá siempre ese número para indicar que ha alcanzado el máximo.

Si probamos con número reales, no tenemos ese problema:

![imagen](https://user-images.githubusercontent.com/33490785/48575256-c4c8a600-e911-11e8-9b09-3c2de3580582.png)

![imagen](https://user-images.githubusercontent.com/33490785/48575321-eb86dc80-e911-11e8-9257-0326cbe96a69.png)

**Comment by alvarag** [comment]
Esto se debe a una confusión o mala interpretación en la comunicación. Cuando yo puse 7,4 me refería a 7 enteros y 4 decimales y no a la sintaxis clásica de SQL que interpreta 7 números de los cuales son 4 decimales.

He repasado la issue #6 , en Fuel la primera vez indiqué:
```
fueCos: numérico 6.2 (6 enteros, 2 decimales)
```

Así que me temo que hay que cambiar todo para tener en cuenta esta interpretación.

**Comment by fransaiz95** [comment]
Efectivamente... Fallo mío. Se me escaparía. Repaso todo y lo echo un ojo.

Gracias Alvar.

**Comment by fransaiz95** [comment]
Alvar, acabo de echar un ojo a esa Issue y efectívamente, el criterio es el que tu has dicho. 6.2, te referias a 6 enteros y 2 decimales, pero si repasamos la tabla regions, pone: 

Region:

    - idRegion: num 5.0
    - name: alfa 100
    - DemFor: 3.4
    - RenFor: 3.4

Los campos DemFor y RenFor pone 3.4, por lo que yo guardé en BBDD MySql el campo decimal 7,4. 
Si el cliente te pasó esas especificaciones, yo en BBDD tengo los datos bien establecidos. 
Si hay que cambiar algo se cambia, que no me importa, pero por dejarlo bien.

**Comment by alvarag** [comment]
Creo que me he perdido... si yo te puse 3.4 y tu lo guardaste como decimal 7.4, está todo bien, ¿no?

**Comment by fransaiz95** [comment]
Está bien si las especificaciones iniciales eran esas, pero el problema que se da en la aplicación ahora mismo, lo que comentabamos al principio con el caso de uso que realizamos para guardar el número 1234, nos guardará por defecto el 999,9999 que es el máximo que permite. Lo dejamos así entonces??

**Comment by alvarag** [comment]
De acuerdo, que yo metí un número superior al límite, ¿no? Creo que debería tener cada campo una ayuda para evitarlo: o bien visual o bien que limite y no permita meter más dígitos de los que luego tenemos en la BBDD

**Comment by fransaiz95** [comment]
Eso es, tu metiste un número mayopr al límite.
Okey, intento el mensaje de validación para indicar que no se puede guardar un número mayor.

**Comment by alvarag** [comment]
Si puede validarse directamente por el campo de entrada del formulario mejor, así evitas dar mensajes al usuario. Pero no sé cómo es de fácil eso en el framework que estas usando

**Comment by fransaiz95** [comment]
Si, eso es lo que voy a hacer, no creo que haya problemas.

**Comment by fransaiz95** [comment]
Jesús, en cuanto a lo que comentabas por mail de las flechas de las cabeceras, están disponibles en aquellas tablas que tienen paginación (o que tienen tan pocos registros que la paginación no aparece, el límite es 10), solo que por defecto, aparece la tabla ordenada por el criterio que yo he seguido en la consulta. Si pinchas en las cabeceras, te aparecerá el cursor pointer y ya aparecerá la flechita para indicar cómo está ordenada esa columna. No se pueden ordenar dos columnas a la vez.
No obstante, repasaré todo para ver si me he dejado alguna tabla.

**Comment by fransaiz95** [comment]
En cuanto al criterio de búsqueda en los buscadores... No se si tiene que ser sensible a mayusculas o no. Yo diría que no, pero como veais.

**Comment by alvarag** [comment]
> En cuanto al criterio de búsqueda en los buscadores... No se si tiene que ser sensible a mayusculas o no. Yo diría que no, pero como veais.

Yo tampoco lo haría sensible a las mayúsculas

**Comment by fransaiz95** [comment]
Buenas noches. Están corregidas las validaciones. 
Espero no haberme dejado nada por ahí. Cada campo numérico tiene su validacion en funcion del tipo de dato y longitud que tenga en BBDD.
