### ISSUE TITLE
Tecnología: falta un campo en el formulario de consulta

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#18]
Ejemplo de alta:

![imagen](https://user-images.githubusercontent.com/9881614/48539912-de89cf00-e8b8-11e8-9d93-3a18527f86c3.png)

En la visualización falta el campo "Gen Cos":

![imagen](https://user-images.githubusercontent.com/9881614/48539984-1abd2f80-e8b9-11e8-9c7a-c6d35a5763e8.png)

_Originally posted by @alvarag in https://github.com/fransaiz95/TFG-Instalaciones-Electricas/issue_comments#issuecomment-438958444_

**Comment by alvarag** [comment]
Otro detalle, en el campo "Fue Cap Emp" se ha colado la cedilla

**Comment by fransaiz95** [comment]
Buenas Alvar, corregido el detalle de la 'Ç' y el campo que se me había olvidado en la visualización de una technología.

Pero no entiendo a que te refieres con el primer pantallazo, donde se muestran unas regiones de portugal que deduzco que habrás creado tu a mano y borrado despues no?

**Comment by fransaiz95** [comment]
Vale, creo que das respuesta a mi pregunta en la otra issue. Se habrán colado los pantallazos.
