### ISSUE TITLE
Diseñar la base de datos MySQL a través de un modelo ER.

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#2]
Una vez configurado el proyecto, mediante un diagrama ER, crearme la base de datos con sus tablas necesarias.

**Comment by alvarag** [comment]
Dejo un esquema orientativo de cómo podría ser la BBDD, a la espera de que Jesús ponga pegas ;)

![entityrelationship](https://user-images.githubusercontent.com/9881614/46063817-25d3c900-c16e-11e8-9e38-30c4015326bb.png)

Paso a esplicarlo:

- Un país tiene regiones (de momento solo tendremos México)
- Las regiones se comunican con arcos (un arco une dos regiones)
- Las regiones tienen tecnologías (plantas de producción)
- Cada planta de producción (tecnología) consume un determinado combustible
- La relación de año con todas las tablas es debido a que un año existen unas plantas y al siguiente puede haber otras (un histórico).

No obstante, esta tarde voy a hablar con el "cliente" de México a ver qué me aclara

**Comment by alvarag** [comment]
Los campos de cada tabla serían (tentativos):

```
TABLE Country {
	idCountry       
	levelDetail     

TABLE Region {
	idRegion        
	idCountry       
	levelDetail     
	demand          
	RenForecast     
	DemForecast     

TABLE Technology {
	idTechnology    
	ExiCapacity     
	CapacityCost    
	GenerationCost  
	CapEmployment   
	GenEmployment   
	EnvImpact       
	GenEmission     
	CapacityEff     

TABLE Fuel {
	idFuel          
	resAvailable    
	fuelCost        
	fuelNational    

TABLE Year {
	idYear          

TABLE Line {
	idLine          
	idRegionOrigin  
	idRegionDestiny 
	exiLine         
	lineCost        
	flowCost        
	lineEmployment  
	flowEmployment  
	lineEfficiency  
```

**Comment by alvarag** [comment]
Tengo que preguntarle sobre la tabla TypeLine que no me queda nada claro qué debería tener...

**Comment by jmaudes** [comment]
Algunas preguntas/comentarios para completar tu entrevista con el cliente:

1) Si "Cada planta de producción (tecnología) consume un determinado combustible", ¿por qué hay 1..N en Fuel en lugar de 1..1?

2) Los de los arcos es una reflexiva de libro

Region N----<conecta>----N Region

y conecta es la entidad Arc
Para que encaje el tipo tendriamos quizás que irnos a una ternaria ¿?

Region N----<conecta>----N Region
                           |
                         N
                     TypeLine
Y generaria una unica tabla Conecta en lugar de las 3 tablas que se deducen del diagrama ( Arc y las 2 relaciones N:N en las que interviene Arc).
Hay una clave en conecta (idRegionOrigen, idRegionDestino, idTipoLinea)
Habria que preguntar si:
a) Entre un origen y destino sólo puede haber un tipo de línea??

Region N----<conecta>----N Region
                           |
                         ¡¡1!!
                     TypeLine
En ese caso la clave es sólo  (idRegionOrigen, idRegionDestino)

a) Los arcos son bidireccionales (tiene importancia la distincion entre origen y destino??)
(Se puede añadir un check en SQL, check(idOrigen<idDestino) para evitar meter el arco inverso...)

Por otro lado no esta claro si la tabla Line representa la entidad TypeLine, Arc y/o algunas relaciones 

3) Lo del año lo entiendo pero no lo acabo de ver con ese encaje. Necesitariamos saber exactamente cuales de todos los datos son fijos y cuales son susceptibles de cambiar anualmente antes de dar otra vuelta al diagrama

Jesus

**Comment by jmaudes** [comment]
Vaya!!!
Me ha descolocado los diagramas!!

Region N--------N Region
|
N
TypeLine

Es

Region N--------N Region
........................|
......................N
..................TypeLine
Donde los "." hay que leerlos como blancos

**Comment by alvarag** [comment]
La de las plantas -- combustible me la sé, es porque algunas plantas pueden quemar diversos combustibles.

El resto se las planteo esta tarde. Gracias Jesús

**Comment by fransaiz95** [comment]
Muchas gracias.

Ya lo he echado un ojo.
Me voy a crear las tablas con los campos como dices y esperaré a ver que te dice en la reunión de esta tarde para terminar de organizar el diagrama y las relaciones entre tablas.

Las sugerencias que hace Jesús me parecen acertadas. Yo la del año tampoco lo entiendo.
Efectivamente, la de los arcos es una reflexiva. Lo que no se es para que son todos los otros campos que por ejemplo en esa tabla se presentan, me imagino que el hombre de México nos contará.

Esta tarde me creo la base de datos con esas tablas y os comento.
A falta de definir el tipo de datos de cada atributo, los que tenga dudas los pondre como varchar(255) y ya lo cambiaré.
