### ISSUE TITLE
¿Puede haber varios arcos entre dos mismas regiones?

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#22]

**Comment by fransaiz95** [comment]
Buenas noches, una dudilla:
¿Se puede dar el siguiente caso en BBDD?

en un registro de la tabla arcs, tener:

- region_1 - region_2 - 250km
- region_1 - region_2 - 300km

Y... 
- region_1 - region_1 - 100km por ejemplo?

**Comment by alvarag** [comment]
Entiendo que en arcs habría que poner una validación para que no permita que origen y destino sean la misma

**Comment by fransaiz95** [comment]
Vale, que no sabía si se debía permitir o no
