### ISSUE TITLE
Error al borrar país

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#23]
Al intentar borrar un país: falla. Yo entiendo que este error se produce porque hay regiones asociadas a ese país y de algún modo tenemos que decirle qué hacer con esas claves foráneas: delete on cascade o lo que sea.

La aplicación deberá tener en cuenta que esto se produce y avisarnos de que no se puede borrar porque hay dependencias, o que borre las regiones asociadas... En cualquier caso: no es de recibo un error sin más que es lo que se produce actualmente.

![imagen](https://user-images.githubusercontent.com/9881614/49140502-b193de00-f2f4-11e8-8a75-42b51f4e155a.png)

**Comment by fransaiz95** [comment]
Efectivamente. No me había dado cuenta. Pasará en más sitios donde haya relaciones.
Yo no soy muy amigo de los deletes en cascada por lo que... Podemos notificar con un mensaje de alerta que esta asociado con otras entidades.

Gracias Alvar.

**Comment by jmaudes** [comment]
A mi tampoco me hacen gracia los deletes en cascada

**Comment by fransaiz95** [comment]
Corregido. 
Este problema lo arrastraremos en todos los deletes. Poco a poco los ire cambiando y solucionando. Podeis hechar un ojo a ese caso concreto para vfer la funcionalidad.
