### ISSUE TITLE
No permitir seleccionar renovable y no renovable a la vez

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#24]
Se trata de una comprobación simple, no parece que tenga mucho sentido que permita seleccionar renovable y no renovable en la búsqueda de Tecnologías. Sería mejor que si selecciona uno se deseleccione el otro.

![imagen](https://user-images.githubusercontent.com/9881614/49140668-26671800-f2f5-11e8-932e-f030cd9b54b6.png)

**Comment by fransaiz95** [comment]
Vale, esto lo puse así por si querían filtrar por todos.
Podemos dejarlo de la siguiente forma:
- Si no tiene nada seleccionado, filtramos todo
- Si selecciona Renewable, deselecciona automaticamente no renewable y viceversa.

**Comment by alvarag** [comment]
Perfecta la solución planteada

**Comment by fransaiz95** [comment]
Completado. Subido al servidor.
