### ISSUE TITLE
Documentacion: 1 Introduccion

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#25]

**Comment by fransaiz95** [comment]
Introducción escrita. No se si tiene que ser esa la estructura, ahora vemos y comentamos.

**Comment by alvarag** [comment]
Ahora echo un ojo a la introducción.

Las fechas que comentábamos ayer: https://www.ubu.es/sites/default/files/portal_page/files/7.calendario_defensa_entrega_de_tfm_y_tfg2018-19_.pdf

**Comment by alvarag** [comment]
La introducción es correcta, tal vez pondría de relieve que el problema de optimización y su solución (el algoritmo) es solicitud de un cliente en México y que tu no has programado nada de esa parte.

**Comment by fransaiz95** [comment]
>La introducción es correcta, tal vez pondría de relieve que el problema de optimización y su solución (el algoritmo) es solicitud de un cliente en México y que tu no has programado nada de esa parte.

Para la administración de todos estos datos, en la figura 1.1, presentamos _Weblectric_, una aplicación desarrollada por petición de un cliente residente en México con la idea de darle la posibilidad de ejecutar su propio algoritmo desde la web y poder administrar los resultados.

Si así está bien, subo el cambio

**Comment by fransaiz95** [comment]
Gracias! ;)

________________________________
De: Álvar Arnaiz-González <notifications@github.com>
Enviado: miércoles, 9 de enero de 2019 16:20:12
Para: fransaiz95/Weblectric2018
Cc: Francisco Saiz Güemes; Assign
Asunto: Re: [fransaiz95/Weblectric2018] Documentacion: 1 Introduccion (#25)


Ahora echo un ojo a la introducción.

Las fechas que comentábamos ayer: https://www.ubu.es/sites/default/files/portal_page/files/7.calendario_defensa_entrega_de_tfm_y_tfg2018-19_.pdf
