### ISSUE TITLE
Documentación: 5 Aspectos relevantes del desarrollo del proyecto

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#29]

**Comment by fransaiz95** [comment]
Buenos días.

He actualizado la memoria con la sección "Aspectos relevantes del proyecto" hecha.

Tengo una duda acerca de algunas librerías que he utilizado en el proyecto y de algún punto que no se si merece la pena explicar y en caso afirmativo, no se donde meterlo, por ejemplo: 
- Librería Select 2 para los formularios.
- Librería Sweet Alert para los mensajes de confirmación.
- Web Ionicons y flaticons para los iconos gratis.
- Jquery.

**Comment by jmaudes** [comment]
Hola Francisco

Aunque parezca increible todavía ando corrigiendo exámenes, cada año hay mas alumnos ...., espero tenerlo acabado el día 2 y hacerte una revisión a fondo de la documentación para entonces
Vete avanzando lo que puedas

Jesus

PD: Necesitamos el boton de restaurar la BD para poder hacer pruebas

El lun., 31 dic. 2018 a las 11:42, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Buenos días.

He actualizado la memoria con la sección "Aspectos relevantes del proyecto" hecha.

Tengo una duda acerca de algunas librerías que he utilizado en el proyecto y de algún punto que no se si merece la pena explicar y en caso afirmativo, no se donde meterlo, por ejemplo:

  *   Librería Select 2 para los formularios.
  *   Librería Sweet Alert para los mensajes de confirmación.
  *   Web Ionicons y flaticons para los iconos gratis.
  *   Jquery.

**Comment by fransaiz95** [comment]
Vale, gracias Jesús. 

Esta tarde hago el botón de restablecer la BBDD a ver si lo saco.
