### ISSUE TITLE
Ir buscando un servidor gratuito en la nube donde poder alojar la aplicación.

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#3]
Para poder tener la aplicación accesible por url, necesitamos un servidor que tenga posibilidad de alojar información y que tenga posibilidad de utilizar MySQL.
Habrá que tener en cuenta cuanto espacio de almacenamiento nos ofrece, y a partir de ahí, tomar alguna decisión.

Toda la información recogida de ventajas y desventajas de cada servicio, recogerlos para más adelante ponerlo en la documentación.

**Comment by alvarag** [comment]
Una nota a tener en cuenta: valora también las opciones de pago disponibles, puesto que el cliente seguramente en el futuro lo despliegue en un servidor pagando por ello.

*Esta mañana me he equivocado y lo he puesto en otra issue :S

**Comment by fransaiz95** [comment]
Vale, he estado mirando diferentes opciones: Me quedo entre estas 2:

[HOSTINGER](https://www.hostinger.es/hosting-web#pricing-table)
Podría coger sin problema la opción premium que ofrece las siguientes caracteristicas:

- 100 Sitios Web  
- 10 GB de SSD por Sitio Web
- Ancho de Banda Ilimitado
- Múltiples versiones de PHP
- PHPMyAdmin
- Acceso FTP

Son características que deberían valer no?
La gran pega que veo es que solo tiene 10GB en SSD. No se cuanto nos ocupará la app. Debería de ser suficiente, pero no se si trabajaremos con archivos o imagenes grandes.

[OVH](https://www.ovh.es/hosting/)
Este hosting, el plan anual es más caro que el anterior pero tambien es valorable. 

- 10 Sitios Web  
- 250 GB de HDD compartido
- 125 usuarios simultaneos
- PHP: 7.2/7.1/7.0/5.6 
- Bases de datos SQL: 3x 400 MB // 1x 2 GB 
- PhpMyAdmin - MySQL 5.6
- Acceso FTP

¿Me aconsejais alguna? ¿Vosotros teneis debilidad por algun hosting en concreto?

**Comment by jmaudes** [comment]
En otros proyectos he visto Nanobox y Heroku; seguramente sean gratuitas o tengan version gratuita aceptable
Echalos un ojo
Yo creo que no vamos a tener 10Gb de datos ni de coña, vamos a ver lo que ocupan las librerias, pero datos imagino seran quizas unas decenas de megas tirando muy por lo alto. Los mapas bitmap estarian en las librerias, no en la base de datos que almacenaría coordenadas de regiones y/o plantas electricas

**Comment by alvarag** [comment]
Como dice Jesús, plantea en la comparativa también ese par de alternativas bastante popular. Con todo ello haces una tabla para la documentación en técnicas y herramientas.
