### ISSUE TITLE
Documentacion: 6 Trabajos relacionados

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#30]

**Comment by alvarag** [comment]
Aplicaciones para comentar en trabajos relacionados:
- Energy Exemplar: https://energyexemplar.com/
- Bentley: https://www.bentley.com/es
- LEAP: https://www.energycommunity.org/default.asp?action=introduction

Artículos científicos:
- https://www.sciencedirect.com/science/article/pii/S0306261916304275

**Comment by alvarag** [comment]
Y de código abierto:
- OSEMOSYS
- SWITCH (de Berkeley)
- Balmorel (de Dinamarca)

**Comment by fransaiz95** [comment]
Buenas, he documentado las 3 aplicaciones que no eran de código abierto y una de las de código abierto, haciendo referencia al artículo científico. No se si es necesario incluir todas en el trabajo. Me decís.

**Comment by jmaudes** [comment]
Hola
Mañana tengo viaje. El 4 viernes me lo miro sin falta (toda la documentación) y te digo
Saludos

Jesus

El mar., 1 ene. 2019 a las 21:22, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Buenas, he documentado las 3 aplicaciones que no eran de código abierto y una de las de código abierto, haciendo referencia al artículo científico. No se si es necesario incluir todas en el trabajo. Me decís.

**Comment by fransaiz95** [comment]
Okey, perfecto. Gracias Jesús.

**Comment by jmaudes** [comment]
Te adjunto revisión del PDF, casi todo lo que he visto son cuestiones de estilo
Alguna cosa también para comentar con Alvar a ver que opina
Sigue trabajando ya queda menos
[memoria_4_enero_.pdf](https://github.com/fransaiz95/Weblectric2018/files/2728176/memoria_4_enero_.pdf)

**Comment by alvarag** [comment]
Estoy de acuerdo con Jesús, si no vamos a explicar el detalle el NSGA-II (que igual tampoco es el objetivo del proyecto), mejor no poner su pseudocódigo.

Si queréis que revise una versión "actualizada" de la memoria me decís y le doy un repaso.

**Comment by fransaiz95** [comment]
Genial, estoy corriegiendo las anotaciones de Jesús. 
Cuando lo tenga os aviso, que me falta poco.

**Comment by fransaiz95** [comment]
Ya he subido la documentación con los cambios anotados por Jesús. He incluido la fecha de visita a la wikipedia en las citas correspondientes y he modificado alguna pues estaba abusando demasiado de la wikipedia, no sabía que no estaba muy bien vista una referencia ahí.

Me falta añadir cita a cada uno de los metodos citados de metodología. Lo demás creo que está todo actualizado.

Gracias!

**Comment by alvarag** [comment]
La memoria va teniendo buena pinta, quedan algunos apartados pero lo que hay está bastante bien, dejo algunos comentarios.

[memoriaC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2733444/memoriaC.pdf)

**Comment by fransaiz95** [comment]
Alvar, en esta aclaración, ¿a qué te refieres?

![imagen](https://user-images.githubusercontent.com/33490785/50783681-dabc6c80-12ab-11e9-8a41-e11e225cd0c8.png)

Que ponga los nombres de los directorios la primera con mayúscula aunque en la estructura de los directorios, se llame con minúscula?

**Comment by alvarag** [comment]
No, a que usaras el comando \verb|config| en vez de \textit{config}, para que quede claro que es el nombre de un directorio/fichero.

**Comment by fransaiz95** [comment]
Ah vale, perfecto.
