### ISSUE TITLE
Documentación: 7 Conclusiones

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#31]

**Comment by fransaiz95** [comment]
Buenas noches, he escrito las conclusiones y las lineas de futuro que se me han ocurrido junto a las propuestas (creo que con acierto) de Jesús.

Si mañana lo podeis echar un ojo, genial, asi por la tarde lo corrijo y lo dejo cerrado para el miercoles llevarlo a imprimir.

Un saludo!

**Comment by alvarag** [comment]
Breves comentarios sobre la memoria:
[memoriaC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2854755/memoriaC.pdf)

**Comment by fransaiz95** [comment]
Gracias Alvar, con esos cambios, quedaría cerrada la memoria?

**Comment by alvarag** [comment]
Igual puede echar un último vistazo Jesús si quiere

**Comment by jmaudes** [comment]
He dado una ojeada a conclusiones y trabajos futuros, porque ya he visto que Alvar ha revisado lo demas a conciencia, y no quiero retrasar mas:

Conclusiones*******************************************
Yo haria mas hincapie en lo que más te diferencia de otros proyectos similares. En ese sentido, el párrafo:

"Para futuros proyectos, se va a adoptar
la idea de poder trabajar con una base de datos de respaldo como se ha
hecho aquí, pues ha sido muy útil para el usuario poder restablecer la base
de datos a su versión de test mediante un botón."

como poco, merece ser un párrafo aislado, pero yo además le alargaría con comentarios en la línea de que los tutores y el alumno han podido probar la aplicación sin temor ha dejar la base de datos en un estado inconsistente o que dificultara pruebas posteriores; y que eso a su vez a permitodo detectar bugs de forma temprana, a lo largo del desarrollo, y no únicamente en la parte final del proyecto; (o algo en esa línea que te permita vender mejor el proyecto)

Trabajos futuros****************************************

"A priori parece un trabajo bastante complejo, pero el alumno
desconoce la existencia de librerías que pudiesen ser de ayuda"
Mejor 
"A priori parece un trabajo bastante complejo, a falta de investigar 
la existencia de librerías que pudiesen ser de ayuda"

Neo4J en cursiva
"Esta estructura es más apropiada para representar arcos pero
se tendría que comprobar el código del algoritmo de optimización,
pues es probable que hubiese que reprogramarlo para que hiciese las
consultas directamente sobre el servidor en un tiempo mucho más
eficiente."
Mejor
"Esta estructura es más apropiada para representar arcos y para hacer consultas sobre arcos, pero
se tendría que adaptar el código del algoritmo de optimización para que tomara los datos de estas nuevas consultas que supuestamente tendrían mejores tiempos de respuesta. A su vez, este cambio conlleva que el algoritmo de optimización acceda al servidor de bases de datos, por lo que lo normal
es que el algoritmo se ejecutase en el servidor".

La integracion con Maps yo la veo como un caso particular de "Valorar si merece la pena definir la topología de la red a través de mapas". Cambialo de sitio o mejor juntalo a esa linea de mejora

Saludos

Jesus

**Comment by fransaiz95** [comment]
Vale, muchas gracias Jesús. Esta tarde realizo los cambios y doy por cerrada la documentación.

Muchísimas gracias.
