### ISSUE TITLE
Dudas documentación & Latex

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#32]

**Comment by fransaiz95** [comment]
Buenas noches. 

He hecho un par de commits con el avance de una primera pincelada a alguna parte de la memoria.
- Objetivos del proyecto
- Conceptos teóricos
- Técnicas y herramientas

Si podeis echarlo un ojo para ver si ese enfoque es correcto, sería genial.

Tengo dudas sobre el resto de puntos: 
- Aspectos relevantes del desarrollo del proyecto
- Trabajos relacionados (entiendo que este es si es continuación o tiene algo que ver con otro proyecto?)

Muchas gracias. Mientras iré avanzando alguna cosilla.

**Comment by fransaiz95** [comment]
Duda de Latex. ¿Como hago para mostrar un link en el texto? por ejemplo, poner un enlace de descarga en el código y que sea clicable.

Muchas gracias

**Comment by alvarag** [comment]
No sé si te refieres a un hipervínculo, si es eso lo puedes hacer con el comando hyperref: https://en.wikibooks.org/wiki/LaTeX/Hyperlinks#\hyperref

**Comment by alvarag** [comment]
> Si podeis echarlo un ojo para ver si ese enfoque es correcto, sería genial.

Mañana echo un ojo y te comento.

> Tengo dudas sobre el resto de puntos:
>     * Aspectos relevantes del desarrollo del proyecto
>     * Trabajos relacionados (entiendo que este es si es continuación o tiene algo que ver con otro proyecto?)

Aspectos relevantes déjalo para el final: podría verse como una retrospectiva de lo que destacas de tu proyecto.

En trabajos relacionados sí que deberás poner otros trabajos/aplicaciones que hagan cosas similares a las que hace tu aplicación. Aquí te pasaré alguna referencia que me deje Rodrigo sobre el tema.

**Comment by alvarag** [comment]
Adjunto el documento de la memoria con comentarios, no te asustes. He puesto muchos comentarios, algunos de estilo, otros de contenido, algunos de LaTeX... La idea es que vayas refinando y cada vez tenga que indicarte menos cosas y vayas siendo más autónomo.

En general está bien.

[memoriaC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2663098/memoriaC.pdf)

**Comment by fransaiz95** [comment]
Vale, muchas gracias Alvar. 
Lo voy corrigiendo

**Comment by fransaiz95** [comment]
He corregido todas las anotaciones de la última revisión y he creado la seccion de Optimización como me sugerías.
He dejado de momento el comentario del pseudocódigo del NSGA-II. Es totalmente necesario? O puedo ir avanzando el resto de puntos y cuando ya lo tenga más cerrado ir puliendo esos detalles?
