### ISSUE TITLE
Deletes de entidades. Si están relacionadas con otra entidad, falla

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#33]
Revisar la aplicación y comprobar dónde se produce error al eliminar algún elemento.

**Comment by alvarag** [comment]
Me parece bien el error que aparece de que no se puede eliminar, pero igual sería aconsejable añadir algo del estilo: Por favor, elimina sus entidades.
Es decir, en vez de: An error was ocurred. The country is associated with a region.
Algo como: An error was ocurred. The country is associated with a region. Please, remove all its region first.

Y que sea un informativo, que no tenga dos botones: Yes / No, (porque no hacen nada distinto cada uno, no?)

**Comment by fransaiz95** [comment]
Vale, quitar el botón "no" me parece correcto. 
Lo de que el botón sea de información en vez de error... No lo termino de ver. Quedaría algo así:

![imagen](https://user-images.githubusercontent.com/33490785/49791182-2d981800-fd30-11e8-86a5-89184b892b47.png)

![imagen](https://user-images.githubusercontent.com/33490785/49791202-3ab50700-fd30-11e8-8d43-9c4f00651370.png)

Yo lo dejaría con la "X" de error, pero lo que tu consideres mejor, no cuesta nada cambiarlo.

**Comment by alvarag** [comment]
No, me refería a que hubiera un botón pero que el mensaje siga siendo de error

**Comment by fransaiz95** [comment]
Vale, genial. Pues lo subo así.
