### ISSUE TITLE
Ordenar la gestión de la app según el cliente

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#34]
Rodrigo (el cliente) ha estado validando la aplicación y tiene algunas sugerencias para cambiar el aspecto o _layout_ de la aplicación. Te voy comentando, espero que quede claro:

1. Pantalla inicial: aparecerían 4 botones: "Countries data", "Technologies", "Objectives" y "Scenarios.
2. Pantalla "Countries data", 4 botones: "Country" (actual "Countries"), "Renewable source" (actual "Range Renewables"), "Climate" (actual "Range meteos") y "Current System".
3. Pantalla "Countries": su idea es que puedas acceder a las regiones desde el país correspondiente (no que tenga un acceso a regiones desde fuera). Y, de este modo, que cuando pinches a regiones de un país, solo aparezcan las regiones de dicho país.
4. Pantalla "Technologies", 4 botones: "Generation technologies" (actual "Technologies"), "Types of lines" (actual "Typelines"), "Fuels" (igual que como está ahora) y "Storage Systems" (esto tengo que hablarlo que no estaba inicialmente, así que igual no lo ponemos).
5. Pantalla "Objectives", 3 botones: "Economic", "Environmental" y "Social". Estas pantallas van a tener una serie de opciones para seleccionar (no trabajan sobre la BBDD) y generarán finalmente el fichero a descargar para la simulación en el PC local.
6. Pantalla "Scenarios", 4 botones: "Demand forecast", "Fuel cost", "Development curve" "Reliability". El qué hará cada uno de ellos habrá que verlo más adelante (no me ha quedado claro).

Espero que más o menos haya quedado claro, cualquier cosa podemos quedar y/o hablarlo.

PD: Hay bastantes cosas que el usuario ahora quiere, pero le tendré que decir que no porque sino se te va a ir de las manos. Estamos casi a mediados de diciembre y hay que darle un empujón bueno si queremos acabar esto (como te comenté).

**Comment by fransaiz95** [comment]
Buenos días Alvar. 
Mucho cambio si. 
De todas formas, hecho en falta algunas de las secciones que antes teníamos que ahora han "desaparecido". 
- La administración general de todos los arcos. Ahora mismo, desde cada región se puede administrar los arcos en los que participa esa región. Antes había una administración general, no se si quiere conservarla.
- La administración de range_demands

No creo que se tengan que eliminar sino que se habrán escapado con el cambio de estructura de la aplicación.

Me comentas si sabes algo y sino preguntamos a Rodrigo dode quiere que se lo pongamos.

**Comment by fransaiz95** [comment]
He subido al servidor los cambios con la nueva estructura, para que avises a Rodrigo y lo compruebe.

**Comment by alvarag** [comment]
> De todas formas, hecho en falta algunas de las secciones que antes teníamos que ahora han "desaparecido".
> 
>     * La administración general de todos los arcos. Ahora mismo, desde cada región se puede administrar los arcos en los que participa esa región. Antes había una administración general, no se si quiere conservarla.
> 
>     * La administración de range_demands
> 
> 
> No creo que se tengan que eliminar sino que se habrán escapado con el cambio de estructura de la aplicación.

Efectivamente, esas tablas son mantenidas desde otro sitio (no desaparecen) pero no me ha quedado muy claro desde dónde :S

**Comment by alvarag** [comment]
Le he pasado la vista actual para que evalúe cómo lo ve: te comentaré lo que me diga.

**Comment by alvarag** [comment]
>     * La administración general de todos los arcos. Ahora mismo, desde cada región se puede administrar los arcos en los que participa esa región. Antes había una administración general, no se si quiere conservarla.

A la administración de arcos se accedería desde país, porque los arcos están asociados a regiones y todo ello debería administrarse desde el país correspondiente.

**Comment by alvarag** [comment]
Ayer estuve hablando con Rodrigo y tengo más cosas claras:

- Current System: ahí va a ir el mantenimiento de los campos Exi. Cap y Exi Lin. Esto se realizará mediante un fichero csv en el que cada fila será una región y cada columna una tecnología.

- Renewable Source: también se realizará mediante un csv. Cada fila será una región y cada columna un momento de tiempo. Se me ocurre que aparezca la tabla de tecnologías renovables y que en cada una permita subir un csv.

- Climate: de momento solo se podrá realizar el mantenimiento de temperatura y tendrá el csv la misma pinta que el anterior.

- Pantalla "Type Lines" poner en la tabla principal solamente los campos "Line cap" y Tension (este último campo no existe pero me enviará sus valores en breve. Es un campo numérico adicional en la tabla.

En la pantalla principal cambia y, en vez de 4 botones habrá 3: Countries Data, Technologies y Simulation. Cuando se pinche en simulation aparecerán 3 botones:
- Objectives
- Scenarios
- Download

**Comment by alvarag** [comment]
En Scenarios habría 3 botones:
- Demand forecast
- Fuel cost
- Development curve

Cada uno de ellos abriría una ventana similar con dos botones:
- Load data: cargaría datos de demanda (desde CSV).
- Forecast: ventana que trataremos más adelante (tras Navidad)

**Comment by fransaiz95** [comment]
Buenas tardes Álvar, tengo varias dudas sobre el penúltimo comentario:

> Current System: ahí va a ir el mantenimiento de los campos Exi. Cap y Exi Lin. Esto se realizará mediante un fichero csv en el que cada fila será una región y cada columna una tecnología.

Estos campos en que tabla se encuentran? Si la estructura del excel que van a subir es esa, deberían estar en la tabla regions_technologies no? Tengo que crearlos?

>Renewable Source: también se realizará mediante un csv. Cada fila será una región y cada columna un momento de tiempo. Se me ocurre que aparezca la tabla de tecnologías renovables y que en cada una permita subir un csv.

Supongo que el dato que tengo que guardar es lo que nosotros llamamos: gen_ava no? En función de ese instante del tiempo que metan ahí. Con el id_region y el id_technology (La idea de hacer la subida por technologies, me parece muy buen idea pues así minimizamos el problema de calculo e inserción de datos a través de los excels.

>Climate: de momento solo se podrá realizar el mantenimiento de temperatura y tendrá el csv la misma pinta que el anterior.

Podríamos utilizar el mismo criterio que lo que proponías antes? Dividir la subida de datos por regiones en este caso? (listandolas todas) Y añadir/actualizar solo los de la region X que seleccione?

> Pantalla "Type Lines" poner en la tabla principal solamente los campos "Line cap" y Tension (este último campo no existe pero me enviará sus valores en breve. Es un campo numérico adicional en la tabla.

Hecho.

>En la pantalla principal cambia y, en vez de 4 botones habrá 3: Countries Data, Technologies y Simulation. Cuando se pinche en simulation aparecerán 3 botones:

Hecha la reorganización de los iconos.
