### ISSUE TITLE
Nuevo campo en la tabla TypeLine

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#35]
Como te comenté, hay que incluir un nuevo campo que no había incluido Rodrigo al inicio en dicha tabla, se trata de la tensión (en kiloVoltios, kV) y es la siguiente:

```
  MW | kV
-----+-----
 100 | 230
 250 | 230
 400 | 230
 500 | 230
 600 | 230
 700 | 230
 800 | 400
 900 | 400
1000 | 400
1500 | 400
2000 | 400
3000 | 400
```

Deberá ser un campo numérico de 4 enteros.

**Comment by alvarag** [comment]
Te habrás dado cuenta de que había dos valores en TypeLine adicionales con más MegaWatios, ¿por qué no están aquí? Sencillo: hay que quitarlas de la BBDD. No deberían haber estado en el Excel inicial

**Comment by fransaiz95** [comment]
Perfecto, pues esta tabla queda de la siguiente manera:
TypeLine: 
- id
- lin_cap
- tension

Con los valores indicados más arriba.

**Comment by fransaiz95** [comment]
La administración de esta sección ya está corregida. 
Cuando me confirmeis que es así, cierro esta issue.
