### ISSUE TITLE
Pantallas de objetivos

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#36]
Imaginar que cada pantalla de Objetivo tiene una serie de ítems que se pueden marcar (checkbox):

Objetivos económicos:
 - [x] Coste de inversión en nuevas plantas
 - [x] Coste de operación y mantenimiento en plantas
 - [x] Coste de generación
 - [x] Coste de inversión en nuevas líneas
 - [x] Coste de operación y mantenimiento de líneas
 - [x] Coste de importación de combustible
 - [x] Coste de políticas públicas

Objetivos medioambientales:
 - [x]  Impacto ambiental
 - [x] Emisión de gases de efecto invernadero
 - [x] Consumo de agua
 - [x] Retiro de agua

Objetivos sociales:
- Empleos en plantas de generación (sería también un check que si se activa activaría todos los de debajo):
  - [x] Empleo en construcción de plantas
  - [x] Empleo en manufactura de equipo
  - [x] Desmantelamiento de plantas
  - [x] Operación y mantenimiento en plantas
  - [x] Empleo generado en producción y transporte de combustible

- Empleo en línea de transmisión (sería también un check que si se activa activaría todos los de debajo):
  - [x]  Empleo en instalaciones en nuevas líneas
  - [x] Empleo en operación en líneas
  - [x] Empleo en mantenimiento en líneas

- Costos sociales (sería también un check que si se activa activaría todos los de debajo):
  - [x] Coste para pública
  - [x] Coste en accidentes producidos
  - [x] Coste energía para usuario

**Comment by fransaiz95** [comment]
Supongo, si he entendido bien, que tengo que poner esos checks en cada una de las pantllas correspondientes a objetivos verdad?
Que funcionalidad tienen? O de momento los pongo y ya está?

**Comment by alvarag** [comment]
Para simplificar, quitamos en simulación el botón de escenarios, quedando solamente: objetivos y descarga.


> Supongo, si he entendido bien, que tengo que poner esos checks en cada una de las pantllas correspondientes a objetivos verdad?

Exacto, en cada pantalla de objetivo pones esos check.


> Que funcionalidad tienen? O de momento los pongo y ya está?

La funcionalidad será a la hora de exportar, que hará que determinados valores vayan a 0 en las hojas de cálculo. Es decir, de momento las pones y ya está.

**Comment by fransaiz95** [comment]
Perfecto, pues a falta de lo demás están colocados.

**Comment by jmaudes** [comment]
A mi que unas cosas esten en español y otras en ingles ... no se ... no se ...
No tiene importancia/dificultad, pero yo lo pondria todo en el mismo idioma, o a lo sumo la frase en ingles mas un salto de linea con la traduccion entre parentesis. Que opinais?

Jesus

**Comment by alvarag** [comment]
Estoy con Jesús, todo al inglés que le da un aspecto más "uniforme": le pregunto a Rodrigo por las traducciones? Son fáciles, pero si prefieres le digo que te las pase

**Comment by fransaiz95** [comment]
Jolín, ni me había fijado, buen apunte si. Todo en inglés, ha sido sin querer.

Las traducciones como veas, las puedo hacer yo, lo único por si quiere poner algo específico.

**Comment by alvarag** [comment]
De algún modo, se deben guardar los objetivos que desee optimizar el usuario. Ahora mismo deja seleccionarlo pero luego al volver a la página no se ha quedado guardado.

**Comment by fransaiz95** [comment]
> De algún modo, se deben guardar los objetivos que desee optimizar el usuario. Ahora mismo deja seleccionarlo pero luego al volver a la página no se ha quedado guardado.

Como hemos comentado esta tarde, ahora se guardan en sesión.
