### ISSUE TITLE
Botón para resetear la base de datos

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#38]

**Comment by fransaiz95** [comment]
Tengo el botón funcionando en el entorno local, el problema es que he tenido que modificar la propiedad `max_allowed_packet` del fichero de configuracion de MySQL `my.ini`. Este archivo no se como modificarlo en el servidor, o siquiera si existe la opción al ser gratuito... Alguna idea?? El límite está en archivos de 1M y necesitaría subirlo a 20 o así.

He intentado desde PHP modificar esos valores pero no tengo acceso como usuario de la base de datos. Se queja de privilegios por lo que tendría que modificarlo desde el servidor. 

Alguna idea??

**Comment by jmaudes** [comment]
He probado el boton, se ha quedado colgado durante 10 minutos y he decidido refrescar la página. Todo parecía OK, pero al entrar en countries me da el error en el pdf adjunto

[Error_ SQLSTATE[42S02]_ Base table or view not found_ 1146 Table 'weblectric.countries' doesn't exist.pdf](https://github.com/fransaiz95/Weblectric2018/files/2727557/Error_.SQLSTATE.42S02._.Base.table.or.view.not.found_.1146.Table.weblectric.countries.doesn.t.exist.pdf)

Parece que borra la tabla pero luego no es capaz de volverla a crear ¿?

La otra cuestión...  No se si entiendo bien el problema del fichero ini. Por que no puedes acceder al servidor de MySQL? Es el servicio de hosting que usas el que te lo impide?

**Comment by fransaiz95** [comment]
>Parece que borra la tabla pero luego no es capaz de volverla a crear ¿?

Claro, es ese el problema. Ahora mismo yo tengo 2 archivitos .sql en el servidor, uno que te ejecuta las sentencias para borrar todas las tablas y otro para crearlas con los datos. El problema es que como en la tabla de las demandas hay muchiiiiisimos datos, el archivo ocupa mucho y por eso lo que comentaba de la necesidad de subir esa variable en el fichero de configuración de MySQL my.ini. O por lo menos, abajo en mi entorno de desarrollo en local, cambiando esa propiedad ya funcionaba.

El error que me daba es este: "General error: 2006 MySQL server has gone away“ que se debe a:
- Se ha alcanzado el timeout del proceso de mysql
- Se ha provocado un error en mysql del que no se ha podido recuperar

[Enlace de interés](https://www.kroatoan.es/trucos-y-solucines/aumentar-max_allowed_packet/)


>Por que no puedes acceder al servidor de MySQL? Es el servicio de hosting que usas el que te lo impide?

Yo tengo acceso al servidor, a través de una dirección ip y un puerto, lo que tengo capados son los privilegios. A continuación dejo un ejemplo:

![imagen](https://user-images.githubusercontent.com/33490785/50698101-5e742000-1044-11e9-943f-72c29a861b78.png)

**Comment by fransaiz95** [comment]
No se si se os ocurre alguna solución: 
- Cambiar de hosting a un plan no gratuito con mas servicios este mes, hasta la entrega. Luego que mire Rodrigo que quiere hacer pues tarde o temprano tendrá que alojarlo en un sitio de verdad.
- Dividir ese sql en inserts chiquititos y en vez de hacer 2 peticiones hacer todas las necesarias.
- ...

Es un problema que vamos a tener tambien a la hora de tratar la subida de excel. Por defecto viene con un valor que habría que cambiar salvo que fragmentemos las subidas y el usuario tenga que hacer más.

No se como se evaluará eso o si habrá problema en ponerlo en alguna seccion de problemas/impedimentos.

**Comment by fransaiz95** [comment]
Podemos quitar de momento de esta funcionalidad los datos de las tablas de demanda y similares. 
De hecho, lo voy a hacer así, por lo menos hasta que de con la solución al tema de los excels.
Se borrarán y se cargarán de nuevo las tablas con datos normales: countries, technologias, fuels, arcs... etc

**Comment by jmaudes** [comment]
Lo de quitar la carga de las excels me parece bien para salir del paso.

Otra idea ... 
Créate un esquema COPIA con las mismas tablas y los datos rellenos, y en lugar de cargar desde fuera de la base de datos, copia los datos desde el esquema copia al esquema en uso
Lo podrías hacer a base de "create table as select ...", pero luego no te tienes que olvidar de hacer alter tables para añadir las restricciones y es un coña...

Por eso, mejor yo vaciaría de datos el esquema principal a base de TRUNCATEs (tendrás que seguir un orden para no violar las FKs) y luego haría inserciones masivas con INSERTs con subconsulta

Esto debería acortar el tiempo de respuesta aunque restaures toda la BD

De todas formas la semana que viene lo hablo con Alvar y vemos cual es la mejor opción, pero si no es mucho coste quizás lo suyo sea cambiar a un plan de pago, asegurándote que incluye esa posibilidad, ya que también tendremos problemas con la cargas de excels que hagan los usuarios, no?

Jesus

**Comment by fransaiz95** [comment]
Buenas Jesús,

vale, de momento he quitado lo de los excels para que tenga funcionalidad, cuando resuelva el tema de trabajar con excels y ya tengamos alimentada todas las tablas, pruebo la solución que me has dicho a ver si con eso nos sirve.

>De todas formas la semana que viene lo hablo con Alvar y vemos cual es la mejor opción, pero si no es mucho coste quizás lo suyo sea cambiar a un plan de pago, asegurándote que incluye esa posibilidad, ya que también tendremos problemas con la cargas de excels que hagan los usuarios, no?

Efectivamente, lo vamos a tener con los excels que suban los usuarios. La próxima semana me gustaría volver a hablar con Alvar esas pantallas a ver si podemos reestructurarlo un poco.

De aquí al martes, voy a seguir dando un palo gordo a la documentación para quitárme cuanto más mejor, que ahí puedo trabajar más por mi cuenta.

Cuando revises lo hecho hasta ahora, me avisas y así corrijo las aportaciones nuevas de aquí al martes.

Un saludo,
Fran

**Comment by alvarag** [comment]
Vuelvo a estar disponible, me parece bien lo de tener una reunión esta semana para ponernos al día y planificar la reccta final.

Un detalle: parece que está caído el servidor, no sé si se debe a las pruebas que has realizado y se ha quedado alguna versión no operativa...

**Comment by fransaiz95** [comment]
Si, me he levantado con el servidor caído. 
Me ha llegado un mail diciendo que hemos alcanzado los recursos disponibles por lo que la cuenta está en estado bloqueado.

Creo que no me va a quedar otro remedio que alojarlo en otro servidor. Déjadme hablar mañana con algún compañero del curro y sino, por la tarde me doy de alta en algún otro sitio de pago con más recursos.

En cuanto a la reunión, yo cuanto antes mejor. Cuando me digais. Sino, como de costumbre.

Un saludo

**Comment by alvarag** [comment]
No recuerdo, ¿hiciste la comparativa de servidores gratuitos/pago en la memoria? Digo por plantearle esa sección a Rodrigo y preguntarle si puede pagarla. De momento no te metas en gastos.

Yo tengo bastante libertad de horarios (ya no hay clases), así que cuando Jesús de el visto bueno.

**Comment by fransaiz95** [comment]
No, no la realicé pues al final tenía dos alternativas: 
- La gratuita que elegí
- Un antiguo alumno de la carrera me ofrecía hosting en un servidor que el tenía montado. Esto era lo que ofrecía:
>Es un servidor compartido con procesador Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 core(s)) y 12GB de RAM con una carga inferior al 20% en la actualidad, así que no debería haber problema de rendimiento. Tiene sistema operativo CentOS 7 gestionado con Plesk. La parte contratada sería de 1GB de espacio SSD en el que se incluye acceso FTP, MySQL, Email y SSH (usuario no root, pero si es necesario realizar alguna tarea root me la puedes pedir para que la ejecute yo si no veo nada raro). No hay limitación en cuanto al número de usuarios FTP, ni bases de datos ni cuentas de correo electrónico ni subdominios, aunque sí estará limitado a 1 dominio al tratarse del paquete básico. En caso de necesitar soporte técnico la vía principal es abrir un ticket (o vía whatsapp / email si te es más cómodo) que se atenderá en menos de 24 horas. El precio para 6 meses es de 18€ + IVA, si necesitas que te gestione un dominio el precio sería de 7,50€ + IVA para el .es o 10€ + IVA para el .com (si buscas otra extensión pregúntame), aunque puedes disponer de un subdominio gratuito del tipo tuproyecto.nesiweb.com

Puedes presentarle esa opción a Rodrigo. A este chico le pregunté al inicio del proyecto pero me imagino que seguirá dando soporte.

**Comment by jmaudes** [comment]
Hola
Yo no he vuelto  hacer mas pruebas desde el día que te reporte el error con el botón de restauración, estaba a la espera de que se resolviera, quizás después de esa nueva reunión

La reunión en principio, jueves a las 18:30 era?
El jueves a las 18:30 tengo tutorías, es una semana complicada, puede que me venga bastante gente a revisar exámenes durante las tutorías (el examen ha salido fatal ... ). Es mejor que dediquemos una hora que no sea de tutorías por si las moscas.

Esta semana tengo las mañanas ocupadas con un curso de la fundación y he tenido que trasladar todas las tutorías a por la tarde. Huecos sin tutorías a última hora de la tarde y que no sea viernes, me queda esto:

Martes a las 19:30
Miércoles a las 19:00 o
Jueves a las 19:30

Como lo véis?

Jesus

El lun., 7 ene. 2019 a las 12:27, Álvar Arnaiz-González (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Vuelvo a estar disponible, me parece bien lo de tener una reunión esta semana para ponernos al día y planificar la reccta final.

Un detalle: parece que está caído el servidor, no sé si se debe a las pruebas que has realizado y se ha quedado alguna versión no operativa...

**Comment by fransaiz95** [comment]
Cualquiera de las 3 opciones me viene bien. 
Por mi lo hacemos el martes y así cuanto antes mejor. Que confirme Alvar con lo que mejor le venga a él.

**Comment by alvarag** [comment]
Pues mañana a las 19.30 y así no perdemos tiempo.

**Comment by fransaiz95** [comment]
Perfecto

El 7 ene. 2019 13:11, Álvar Arnaiz-González <notifications@github.com> escribió:

Pues mañana a las 19.30 y así no perdemos tiempo.

**Comment by jmaudes** [comment]
Ok, mañana martes a las 19:30

Jesus

El lun., 7 ene. 2019 a las 13:15, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:
Perfecto

El 7 ene. 2019 13:11, Álvar Arnaiz-González <notifications@github.com<mailto:notifications@github.com>> escribió:

Pues mañana a las 19.30 y así no perdemos tiempo.
