### ISSUE TITLE
Administración hoja de calculo Climate (rangemeteos)

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#39]
Volver a estructurar la función que lee del excel para ver si el problema de la memoria es cuestión de un mal uso de transacciones, si la librería no permite trabajar con tantos datos, si es un bug del código o un problema externo.

Dar diseño a la pantalla y crear la administración.

Dudas y discusiones anteriores: [Carga de datos producción/demanda #16](https://github.com/fransaiz95/Weblectric2018/issues/16)

**Comment by fransaiz95** [comment]
[Dudas y discusiones anteriores:](https://github.com/fransaiz95/Weblectric2018/issues/16)

**Comment by fransaiz95** [comment]
Buenas tardes, esto tiene buena pinta. Tengo una pregunta en cuanto a eficiencia de sql.

Hay alguna alternativa a poder hacer un "truncate con una condicion?" por ejemplo... "truncate arcs where id_region = 3"

Con condición, solo se puede usar el "delete from..."? 

He conseguido realizar varias importaciones utilizando truncate previamente, pues si el excel es para el año 2018, necesito borrar previamente los datos para insertar los nuevos pues es un jaleo andar comprobando si ya existe el registro, yo creo que es menos eficiente.

Lo que quiero saber es qué forma es la más eficiente de borrar todos los datos acordes al 2018.

**Comment by alvarag** [comment]
Que me corrija Jesús si me equivoco pero, hasta donde yo se:

- Truncate: muy rápido pero no hace _enemigos_, es decir, que se carga todo el contenido de la tabla.
- Delete: perdemos velocidad, pero podemos restringirlo por la cláusula WHERE.

Me gusta lo de que te puedas descargar una hoja de cálculo con la plantilla, pero ahora mismo es demasiado pesada y grande (ocupa unos 3MB) y hace que tarde mucho.
Creo que sería suficiente con que se descargue unos pocos registros, ej: un día entero (con sus horas y sus regiones), así ya coge el usuario la idea y descargará mucho más rápido.

**Comment by fransaiz95** [comment]
Lo del truncate y delete si, eso es lo que yo tenía entendido, no pasa nada. Tengo que usar delete pues hay que pasarle la condición del año a la hora de ver que datos borrar y actualizar.

Esta era una de las cosas que me gustaría hablar con vosotros si.

La idea de descargar toda la plantilla es por ejemplo si ya hay un dato para la region X en un día del año, que tu puedas ir directamente a esa celda en la plantilla y modificar el dato y subir ese excel tal cual. 

Esto debería de ser así porque siempre que se sube una hoja de cálculo, se eliminan los datos de ese año y se meten los del excel, pues sino, andar comprobando si existe o no ese dato para cada uno de los datos puede ser mucho más largo y pesado.

Quizá podríamos cambiar el texto del botón que se llame "Download all data" o algo así, en vez de template.

**Comment by alvarag** [comment]
Sí, podría ser: Download current data. Una cosa, si es por año, igual tendría que aparecer un selector de los años que hay cargados para que puedas descargarte el año que te interese

**Comment by fransaiz95** [comment]
Vale si, me parece bien que haya un selector de años.

**Comment by jmaudes** [comment]
Efectivamente, el truncate es específico para borrar todas las filas de un tabla
No se si tardaria mas en:

Opcion 1: Delete WHERE
Opcion 2: INSERT AS SELECT WHERE de las filas a preservar en una tabla temporal + TRUNCATE + INSERT AS SELECT desde la tabla temporal

Lo lógico es que el delete en solitario vaya mejor y ademas genere menos bloqueos

Jesus

PD: Perdon por tardar en responder


El jue., 17 ene. 2019 a las 12:23, Álvar Arnaiz-González (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Que me corrija Jesús si me equivoco pero, hasta donde yo se:

  *   Truncate: muy rápido pero no hace enemigos, es decir, que se carga todo el contenido de la tabla.
  *   Delete: perdemos velocidad, pero podemos restringirlo por la cláusula WHERE.

Me gusta lo de que te puedas descargar una hoja de cálculo con la plantilla, pero ahora mismo es demasiado pesada y grande (ocupa unos 3MB) y hace que tarde mucho.
Creo que sería suficiente con que se descargue unos pocos registros, ej: un día entero (con sus horas y sus regiones), así ya coge el usuario la idea y descargará mucho más rápido.

**Comment by fransaiz95** [comment]
Delete + WHERE estoy usando y bien, este problema esta resuelto si
