### ISSUE TITLE
Crear la estructura de directorios del proyecto

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#4]
Crear la estructura básica de directorios, ejemplo:
- App: web
- Doc: documentación

Pregunta, ¿has conectado zenhub y asignado las horas? Yo no consigo verlas, ¿igual es por ser privado tuyo?

**Comment by fransaiz95** [comment]
ZenHub lo tengo conectado si. Si que he asignado las horas a cada Issue. ¿Dices por ser proyecto privado?
¿Puedo configurarlo de tal manera que podais verlo?
Si es así, lo pongo público.

**Comment by alvarag** [comment]
Supongo que si fuera público podríamos verlo también con Zenhub nosotros. Pero da igual.

**Comment by fransaiz95** [comment]
Pues lo que me digais, no me importa ponerlo público
