### ISSUE TITLE
Current system: Exi cap & exi lin

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#40]
Current System: ahí va a ir el mantenimiento de los campos Exi. Cap y Exi Lin. Esto se realizará mediante un fichero csv en el que cada fila será una región y cada columna una tecnología.

[Ordenar la gestión de la app según el cliente #34](https://github.com/fransaiz95/Weblectric2018/issues/34)

**Comment by fransaiz95** [comment]
[Ordenar la gestión de la app según el cliente #34](https://github.com/fransaiz95/Weblectric2018/issues/34)

**Comment by fransaiz95** [comment]
Alvar, si puedes preguntar al cliente donde guardamos estos campos, genial.

**Comment by alvarag** [comment]
Tanto Exi Lin como Exi Cap se mantienen a través de sendas hojas de cálculo a las que se debería acceder por Current System.

Exi Cap tiene la capacidad de cada región por cada tecnología. Imagina una hoja de cálculo que tiene tantas columnas como tecnologías y tantas filas como regiones. En cada celda tiene la capacidad de una tecnología en una región.
Por lo tanto, la información de aquí tiene que ir a alimentar la tabla que relaciona Tecnología con Región.

Exi Lin contiene la información de las líneas o arcos. Cada fila es una línea concreta (o un arco) que conecta dos regiones. Por lo tanto, sería una hoja de cálculo con 4 columnas y tantas filas como líneas.
- Columna 1: región inicio de línea (el ID de la región).
- Columna 2: región final de línea (el ID de la región).
- Columna 3: tipo de línea. Tenemos líneas de 100MW, 250MW, etc.
- Columna 4: longitud de la línea (en kilómetros).

**Comment by alvarag** [comment]
Viendo ahora en detalle el mantenimiento de arcos desde las regiones, entiendo que la información de Exi Lin ya está introduciéndose ahí, ¿no?
Revisa esto porque igual solamente hace falta Exi Cap (en caso de que lo otro ya esté desde otro sitio)

**Comment by fransaiz95** [comment]
Efectivamente, lo que el llama Exi Lin es lo que nosotros tenemos como Lin Cap. En la relación entre un arco y el tipo de linea.

Lo cambiamos de nombre o que hacemos??

**Comment by alvarag** [comment]
Creo que no es necesario el cambio, simplemente tenerlo en cuenta.

**Comment by alvarag** [comment]
Recuerda incluir un aviso en la descarga de datos desde csv de que el proceso puede tardar. Ya que sino parece que es un error.
