### ISSUE TITLE
Mejorar botón para actualizar base de datos mediante un Schema copia

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#41]
Continuación de la issue: [Botón para resetear la base de datos #38](https://github.com/fransaiz95/Weblectric2018/issues/38)

**Comment by fransaiz95** [comment]
Hecho. Ahora tarda bastante menos si. Mejor solución!

**Comment by alvarag** [comment]
La restauración va muy rápida, lo cual es perfecto.

Lo único que hecho en falta, es que cuando ha hecho la restauración no recarga la página y el usuario puede pensar que no se han hecho los cambios.
