### ISSUE TITLE
Buscar nuevo alojamiento para la web

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#42]
Debido a que el hosting gratuito se queda limitado de recursos, tenemos que buscar otras opciones para contratar un nuevo servicio.

[Muestra de la app en el servidor #15](https://github.com/fransaiz95/Weblectric2018/issues/15)

**Comment by fransaiz95** [comment]
Buenas tardes, ya tengo alojada la web en otro servidor.

Este es el enlace: [https://www.proyectoubu.nesiweb.com/](https://www.proyectoubu.nesiweb.com/)

lo cambio tambien en el readme

**Comment by jmaudes** [comment]
OK

Comprobado que accedo bien

Jesus

El lun., 14 ene. 2019 a las 21:31, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Buenas tardes, ya tengo alojada la web en otro servidor.

Este es el enlace: https://www.proyectoubu.nesiweb.com/

lo cambio tambien en el readme

**Comment by alvarag** [comment]
¿Hay algún problema con https? A mí me aparece la alerta de seguridad: funciona, pero no queda muy "serio".

![imagen](https://user-images.githubusercontent.com/9881614/51181700-22ef1680-18cc-11e9-90c8-349bbdd1aa93.png)

**Comment by fransaiz95** [comment]
Yo creo que eso es porque está configurado el servidor para que tire con https y yo en el proyecto no lo tengo configurado. Busco solucionarlo si.
