### ISSUE TITLE
Anexos: A Plan de proyecto

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#43]

**Comment by fransaiz95** [comment]
Buenas noches, tengo un problema con los _Burndown report_.
Durante todos los sprints, he estado marcando las issues completadas como "done" para poder tenerlas accesibles y solo al final del sprint, las pasaba todas como closed.
¿Cuál es el problema? Que todos o casi todos los _Burndown report_ son de este pelo:

![imagen](https://user-images.githubusercontent.com/33490785/50928627-793b0000-145b-11e9-91d8-1580cd64b498.png)

¿Hay alguna solución?

**Comment by alvarag** [comment]
No pongas los burndown chart, no son obligatorios.

**Comment by fransaiz95** [comment]
Vale, perfecto.

**Comment by fransaiz95** [comment]
Tengo otra duda, los anexos, a la hora de ir describiendo la planificación, en que tiempo verbal hay que narrarlo? Asi como en la memoria predominaba la forma impersonal, aqui tenemos que narrarlo de la misma manera? En presente?

Gracias!

**Comment by fransaiz95** [comment]
Buenas noches, 

he subido una primera versión del primer anexo: _Plan de proyecto._ Faltan sprints que tendré que ir metiendo a medida que avancemos hasta el final y actualizar los datos del estudio de viabilidad económica. Me decís si así tiene buena pinta

Tengo una duda acerca del estudio de viabilidad legal. Los tipos de licencias y su clasificación y demás, tengo que investigar yo cómo se distribuyen? O hay algún patrón?

Gracias!

**Comment by alvarag** [comment]
En planificación puedes narrarlo en dos tiempos: lo que ibas a hacer en futuro y lo que has hecho en pasado. Pero también puedes todo en pasado.

En cuanto a la forma impersonal, siempre deberías usarla tanto en memoria como anexos

**Comment by alvarag** [comment]
> Tengo una duda acerca del estudio de viabilidad legal. Los tipos de licencias y su clasificación y demás, tengo que investigar yo cómo se distribuyen? O hay algún patrón?

Tienes que evaluar/anotar las licencias de los diversos software que estes utilizando. Con todo ello, quedarte con la más restrictiva para darle dicha licencia a tu proyecto

**Comment by fransaiz95** [comment]
A falta de ir rellenando el apartado con los siguientes sprints, este apartado del anexo estaría terminado. Ya me direis si el formato y el desarrollo es correcto.

**Comment by jmaudes** [comment]
Te mando una revisión entera de los anexos a fecha de hoy
Lo meto en esta issue pero he revisado TODOS los anexos, hay pequeños comentarios en el PDF adjunto

[anexos.pdf](https://github.com/fransaiz95/Weblectric2018/files/2775873/anexos.pdf)

En geberal bien, faltan cosas por completar, pero lo que ya esta hecho tiene poco que comentar por mi parte

**Comment by jmaudes** [comment]
Lo has cerrado, pero sin embargo hay unos puntos suspensivos antes de la seccion A3, y en general la sección A3 esta plagada de XXXs e YYYs


El lun., 21 ene. 2019 a las 21:30, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Closed #43<https://github.com/fransaiz95/Weblectric2018/issues/43>.

**Comment by fransaiz95** [comment]
Buenas noches, a falta de una revisión final, el anexo A Plan de proyecto, estaría terminado.

**Comment by alvarag** [comment]
¿Cuáles puedo revisar entonces? Es para dejarte una versión lista esta tarde

**Comment by fransaiz95** [comment]
Este, el anexo A.

**Comment by alvarag** [comment]
Comentarios hechos en el Anexo A.

[anexosC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2827991/anexosC.pdf)
