### ISSUE TITLE
Anexos: C Diseño

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#45]

**Comment by fransaiz95** [comment]
Buenas noches. He escrito el anexo C correspondiente al Dieseño. Ya me direís si es correcto.

Gracias!

**Comment by alvarag** [comment]
En general está correcto, pero hay cosas que añadir.

[anexosC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2754458/anexosC.pdf)

Vigila la redacción, trata de usar el impersonal tanto como sea posible (revisa todo, que no he ido marcando todos esos cambios).

**Comment by fransaiz95** [comment]
Perfecto, gracias Álvar.

**Comment by alvarag** [comment]
¿Qué tal va el diccionario de datos? Es importante ese punto como dijo Jesús. No sé si tienes la descripción de todos los campos entre lo que nos pasaron en la carga y el documento que  te pasé esta semana. Sino me dices y lo miramos.

**Comment by fransaiz95** [comment]
Buenas, no lo he hecho no, pensé que ayer me iba a dar tiempo a hacerlo ayer pero no. 
Esta tarde me pondré con ello y los campos que me falten te digo.

**Comment by alvarag** [comment]
Bien, lo comento porque una vez tengamos identificado cada campo: debería ser sencillo hacer la exportación y poder dar por terminada la aplicación (en la próxima reunión).
