### ISSUE TITLE
Añadir migas de pan

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#46]
Es fácil perderse en la versión actual, ¿cómo sería de fácil añadir unas migas de pan para saber dónde se encuentra el usuario y poder navegar?

**Comment by fransaiz95** [comment]
Me parece buena propuesta, todo es mirar a ver lo que puedo tardar.
Esta tarde quiero terminar lo de la importación desde excels. En función de como vaya, voy mirándolo.

**Comment by alvarag** [comment]
Esto es una mejora, si cuesta mucho se deja como línea futura

**Comment by fransaiz95** [comment]
Tarea completada y subida al entorno de producción. 
Si veis algo raro o proponeis otra cosa, me decís.

**Comment by alvarag** [comment]
Yo haría un poco más grande la fuente en las migas, y que apareciese siempre (aunque esto es opcional).

¿Se podría hacer que saliera siempre? También cuando estamos en la edición de un formulario concreto?

Me pasa un poco lo mismo con el botón back, que a veces aparece arriba, otras no aparece y otras un poco más abajo... puede despistar un poco al usuario. Aunque si esto es costoso tampoco es primordial

**Comment by fransaiz95** [comment]
Vale, están puestas hasta el final del flujo con la fueste un poco más grande.
He intentado colocar en todos los sitios el botón back en el mismo lado. Por coherencia lo deberían de llevar todas las pantallas, si se me escapa en algún sitio me avisais.

**Comment by alvarag** [comment]
Falta en: [Country](https://www.proyectoubu.nesiweb.com/countries/view/1)

![imagen](https://user-images.githubusercontent.com/9881614/51591484-6578aa80-1eed-11e9-96e6-dac9cdf8e855.png)

En los [Fuels](https://www.proyectoubu.nesiweb.com/fuels/view/1) el botón de "Back" está en donde no debería:

![imagen](https://user-images.githubusercontent.com/9881614/51591561-a07ade00-1eed-11e9-90fa-00fa6fd045a9.png)

**Comment by fransaiz95** [comment]
Okey, corregido.

**Comment by alvarag** [comment]
En la visualización y mantenimiento de [Countries](https://www.proyectoubu.nesiweb.com/countries/view/1) y [Regions](https://www.proyectoubu.nesiweb.com/regions/view/1) desaparecen las migas (no sé si intencionado).

Cuando das a "[Back](https://www.proyectoubu.nesiweb.com/)" en [Regions](https://www.proyectoubu.nesiweb.com/regions/home), te vas hasta la pantalla principal.

**Comment by fransaiz95** [comment]
> En la visualización y mantenimiento de Countries y Regions desaparecen las migas (no sé si intencionado).
Cuando das a "Back" en Regions, te vas hasta la pantalla principal.

Se me había escapado un archivo en la subida... Ya está actualizado
