### ISSUE TITLE
Pantallas duplicadas

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#47]
Con la nueva distribución de Rodrigo, creo que tenemos que cambiar una pantalla. De hecho me suena haber visto cambios, tal vez me estoy adelantando con esta issue:

- Countries Data -> Renewable Source: sólo deberían aparecer las renovables, no tiene sentido el buscador por renovables/sucias. Aquí, como bien tienes, se cargarán datos con una hoja de cálculo.

- Technologies -> Generation technologies: podemos hacer que aparezcan todas (renovables/no renovables), aunque aquí no se carga hoja de cálculo. Es decir, esto lo dejamos como lo tienes.

**Comment by fransaiz95** [comment]
Vale, me arece bien el apunte, tiene sentido. Para la carga de datos de las renewables source, dejamos solo las tecnologias renovables.

**Comment by alvarag** [comment]
Ahora ya veo que desde Countries no se ven las no renovables: OK

Pero desde Technologies deben verse todas (como antes). Por defecto creo que estás dejando el filtro activo.

**Comment by fransaiz95** [comment]
Ains... Que se me ha ido la consulta, fallo mío, no quería dejarlo así, lo corrijo cuando pueda.
