### ISSUE TITLE
Mantenimiento de regiones

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#48]
Con la nueva distribución, creo que hemos perdido la posibilidad de mantener las regiones. Me parece que lo lógico es que accedas a mantener las regiones desde país.
Por ejemplo, das a editar un país y que te salgan sus regiones (y puedas visualizar, crear o modificar)

**Comment by fransaiz95** [comment]
Buenas tardes Alvar, efectivamente, con la nueva distribución, las regiones quedaron accesibles desde los countries.

[countries home](https://www.proyectoubu.nesiweb.com/countries/home)

Desde el lapiz se edita el pais, en este caso solo tiene un campo nombre, desde el ojo, el tooltip indica "view regions" y desde ahi se ven las regiones y se pueden modificar.

**Comment by alvarag** [comment]
Genial entonces
