### ISSUE TITLE
Bugs o malentendidos

### ISSUE THREAD

**Issue by jmaudes** [fransaiz95/Weblectric2018#49]
Te voy dejando aquí cosas que creo no van bien, o a lo mejor van bien pero soy yo el que no lo entiendo bien

**Comment by jmaudes** [comment]
Doy de alta un pais, Luego en la pantalla de Country lo busco con search, me va a la pantalla de Fuels. Es correcto?

**Comment by jmaudes** [comment]
Cuando voy a hacer download de la hoja Climate tarda del orden de 3 minutos. Son un par de megas, es normal? Lo mismo algún mensaje avisando que puede tardar unos minutos

**Comment by jmaudes** [comment]
Estoy intruduciendo una energia renovable, como hay muchos campos solo ha metido los primeros y me da el error SQL adjunto, que en un principio pense que era por no llenar algun campo obligatorio que el intenta llenar con cero

![bug_pk_cero](https://user-images.githubusercontent.com/1501818/51439056-295b0500-1cb5-11e9-8491-5a86734b3a4b.PNG)

 Es posible que tenga que ver con que con anterioridad inserté otra fuente de energia (en este caso no-renovable) y ya introdujera un cero en la PK de esa primera insercion, y ahora al hacer una nueva inserción, vuelva a poner otro cero y casque

Quizas seria bueno indicar con * los campos obligatorios siempre, y validarlos en el navegador antes de mandar la peticion al servidor, asi evitariamos que salgan errores SQL por este tipo de cosas que son tan habituales

**Comment by jmaudes** [comment]
El bug anterior también ocurre cuando inserto 2 tipos de arcos, y me temo que es un problema generalizado a cuando insertamos 2 itemes cualquiera que sean. El primer item va bien, pero cuando insertas el segundo te dice que has violado la PK porque es la segunda vez que intentas que la PK valga cero

![bug_pk_cero_tiposarcos](https://user-images.githubusercontent.com/1501818/51439161-77243d00-1cb6-11e9-9e28-2e74d69de2ee.PNG)

**Comment by jmaudes** [comment]
Estoy en la pantalla de Fuels
Doy al ojito en uno de los fuels
Aparece la lista de las tecnologias de ese fuel
Borro una tecnología de ese fuel
Me aparece este mensaje para que me lo piense

![delete_tech](https://user-images.githubusercontent.com/1501818/51439214-37aa2080-1cb7-11e9-9f0e-8d143f6846b7.PNG)

Lo que me choca es la palabre region en el mensaje de error. Esta bien y soy yo el que no lo entiendo?

**Comment by jmaudes** [comment]
Ahora borro una tecnología de un fuel a pesar del mensaje de advertencia
(He intentado borrar BED de Biogás)
Sale esto:
![delete_tech_controller_err](https://user-images.githubusercontent.com/1501818/51439251-b43cff00-1cb7-11e9-9d30-2cb50eab3a5f.PNG)

**Comment by fransaiz95** [comment]
Buenas Jesús, acabo de verlo que he estado con los anexos. Efectivamente son errores, muchas gracias.
Mañana despues de la reunión los corrijo.
