### ISSUE TITLE
Anexos: D Manual del programador

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#50]

**Comment by fransaiz95** [comment]
Buenas noches, he realizado un commit con las pequeñas correcciones que me habeis hecho de los anexos anteriores y alguna de las correcciones más significativas. He metido los dos dibujos que sugeríais para los casos de uso de importacion mediante hojas de calculo y el de restablecer la base de datos, espero que sean correctos.

He realizado un diagrama de despliegue que no he introducido en ningún sitio pues no se muy bien en que apartado, mañana me comentais. El dibujo es este:

![diagrama de despliegue](https://user-images.githubusercontent.com/33490785/51446310-a4053e00-1d10-11e9-86e6-c63300a0235e.png)

He escrito tambien el anexo del manual del programador intentando ser lo más explícito posible, no se si así será correcto. Mañana lo vemos.

Un saludo.

**Comment by jmaudes** [comment]
Manual del programador revisado, algun acento, poca cosa
Ten cuidado con algunas cosas raras te hace Latex, pregunta a Alvar

[anexos (22 enero revision manual prog).pdf](https://github.com/fransaiz95/Weblectric2018/files/2783807/anexos.22.enero.revision.manual.prog.pdf)

**Comment by alvarag** [comment]
El que se "monten" el apéndice con el número de página es un error detectado en la plantilla... Hay que cambiarlo pero todavía no lo ha hecho nadie: no te preocupes por ello.

Para los fragmentos de código en línea, en vez de $$ ó \textit lo mejor es usar una fuente monoespaciada: \texttt{texto}
