### ISSUE TITLE
Mantenimiento de Fuels

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#51]
No sé si creé una issue y se me olvidó guardarla o ya se me va la cabeza...

Tenemos Fuels, y cada fuel se usa en una o más centrales de producción, ¿verdad?

Mis preguntas son:

![imagen](https://user-images.githubusercontent.com/9881614/51493648-45929b00-1db6-11e9-8713-7d40c20032fa.png)

- ¿Para qué es el botón superior con el engranaje y la llave?
- ¿Tiene sentido borrar tecnologías desde aquí?
- Parece que la cantidad de combustible que puede quemar cada tecnología no la estamos mostrando en ningún sitio, ¿está y se nos olvida mostrarla o no nos ha dicho el cliente dónde ponerla?

**Comment by alvarag** [comment]
Relacionado con esto, sería el por qué las tecnologías aparecen en distinto orden en esta pantalla que en la de tecnologías.

![imagen](https://user-images.githubusercontent.com/9881614/51493803-c487d380-1db6-11e9-9f96-3b770c1b3c47.png)

**Comment by fransaiz95** [comment]
> Tenemos Fuels, y cada fuel se usa en una o más centrales de producción, ¿verdad?

Eso es si. Los fuels están relacionados con las technologies.

>¿Para qué es el botón superior con el engranaje y la llave?

Estaba puesto para indicar que es la pantalla de fuels relacionado con las technologies (Ese es el icono de las technologies), pero si despista lo quito. Aquí solo hay uno porque los fuels no tienen mas relaciones, en la pantalla de las [regions](https://www.proyectoubu.nesiweb.com/regions/view/1) tenemos technologies y arcs(que faltaría el color del hover al ponerte encima por lo que veo.

> ¿Tiene sentido borrar tecnologías desde aquí?

Desde aquí no borras tecnologías como tal. Borras las tecnologias asociadas a ese fuel. (Se borran registros de la tabla fuels_technologies)

> Parece que la cantidad de combustible que puede quemar cada tecnología no la estamos mostrando en ningún sitio, ¿está y se nos olvida mostrarla o no nos ha dicho el cliente dónde ponerla?

Esto que campo es? Esa información no es ninguno de los campos "power", "perc_con" ni "fue_con"?

**Comment by fransaiz95** [comment]
>Relacionado con esto, sería el por qué las tecnologías aparecen en distinto orden en esta pantalla que en la de tecnologías.

Lo reviso a ver si, será el orden de la consulta.

**Comment by alvarag** [comment]
Igual es culpa mía, que estoy ya un poco perdido... Pero yo tenía entendido que teníamos una relación varios a varios entre Fuels y Technology. Y esa relación indicaba qué combustibles podía quemar una tecnología concreta.

Por ejemplo, una de cogeneración: puede quemar gas natural y también gas butano. 

Si no me equivoco, había dos campos en la relación:

- Uno para el porcentaje de aportación de combustible.
- FueCon: consumo de combustible necesario para generar un MW

**Comment by fransaiz95** [comment]
Si, yo creo que estamos haciendo referencia a lo mismo. Intento explicar la pantalla de la relación entre un fuel y una techologia: En la pantalla del primer pantallazo (Carbón en este caso) aparecen mezclados los siguientes datos:

![fuels_technologies](https://user-images.githubusercontent.com/33490785/51522960-df942b00-1e2a-11e9-84cb-931f7dee41b0.png)

**Rojo:** Los datos del fuel.
**Verde:** Algunos datos de la technology.
**Azul:** Los tres campos que tenemos en la relación N...N entre los fuels y las technologies. Supongo que los datos a los que te referías son estos:
- Power:
- Perc Con: El porcentaje de aportación de combustible. 
- Fue Con: Consumo de combustible necesario para generar un MW

Las actions dentro del recuadro azul son para eliminar registros de la relación N...N entre fuels y technologies.

No se si nos estamos entendiendo, espero que sea correcto lo que acabo de indicar, sino, habrá que cambiarlo pues no lo entendí yo bien en su momento.

No obstante, si hay cosas que no se entienden bien, lo cambiamos.

**Comment by alvarag** [comment]
Vale, eso sí me cuadra. Lo único que igual hay que cambiar un poco porque si borramos una tecnología: ¿cómo se podría volver a dar de alta? 

Por otra parte, se lo preguntaré hoy a Rodrigo, me parece más fácil de ver el acceder desde Tecnología y que tenga los fuels que al revés (pero esto lo tiene que confirmar él)

**Comment by fransaiz95** [comment]
> Vale, eso sí me cuadra. Lo único que igual hay que cambiar un poco porque si borramos una tecnología: ¿cómo se podría volver a dar de alta?

Si, visto lo visto, faltaría el poder dar de alta una nueva relación entre el fuel seleccionado y alguna technologia. Podríamos poner un botón para añadir y editar cada una de esas relaciones. 

> me parece más fácil de ver el acceder desde Tecnología y que tenga los fuels que al revés (pero esto lo tiene que confirmar él)

Vale, pregúntaselo y con lo que el diga decidimos.

**Comment by alvarag** [comment]
Creo que lo mejor igual es eso, que aparezca para un combustible todas las tecnologías. Ahí el usuario puede editar los campos de si las tecnologías pueden quemar o no ese combustible.

**Comment by fransaiz95** [comment]
Genial, pues lo dejamos como está a espensas de poder añadir y editar, que falta el desarrollo.

**Comment by fransaiz95** [comment]
Administración terminada, ya se pueden añadir, editar y eliminar fuels_technologies y regions_technologies, que tambien faltaba por hacer.
