### ISSUE TITLE
Anexos: Explicar diagramas ER y relacional

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#54]
- [ ] Descripción de los diagramas.
- [ ] Cambiar aceites -> Combustibles.
- [ ] Claves subrayadas.
- [ ] Diccionario de datos.

**Comment by alvarag** [comment]
Para el diccionario de datos, puede serte de utilidad este documento que me pasaron. En él aparecen los campos necesarios luego para la exportación y creo que podrás ir sacando la descripción de los campos.

[leeme.pdf](https://github.com/fransaiz95/Weblectric2018/files/2781899/leeme.pdf)

**Comment by fransaiz95** [comment]
Buenas tardes, he estado fuera el fin de semana por lo que no he podido ponerme hasta esta tarde.

Tengo casi todos los campos identificados. Me faltan los siguientes:
- fuels_technologies:
  - power
- Technologies:
  - life_time
  - inv_cap_emp
  - man_cap_emp
  - dec_cam_emp
  - om_cap_emp
  - fue_cap_emp

**Comment by alvarag** [comment]
Esos campos no aparecen en el último documento que te envié, ¿verdad? Es para enviarle directamente a Rodrigo estos campos y que nos los verifique

**Comment by fransaiz95** [comment]
Eso es, no aparecen.

**Comment by alvarag** [comment]
De acuerdo, se lo pregunto ahora mismo por e-mail y te comento cuando me conteste.

**Comment by fransaiz95** [comment]
Perfecto!

**Comment by fransaiz95** [comment]
Buenas noches, a falta de que Rodrigo nos responda con el significado de los campos que se han comentado, he puesto un tooltip en cada uno de los labels de los formularios.

Creeis que es bueno ponerlo en todos los sitios? Me explico, tambien en las cabeceras de las t6ablas y donde se pinten con texto los valores? Igual queda demasiado recargado, pero me decís.

Un saludo.

Mañana lo iré metiendo en la documentación.

**Comment by jmaudes** [comment]
Mi opinion es que si los tooltips tienen el mismo texto que se supone van a explicar, no tienen utilidad
Esta muy bien que los pongas, pero aun cuando sean evidentes, es de mal efecto que tenga el mismo texto y que no los acompañes con una frasecilla

En cuanto a que quede recargado, una posibilidad es que como regla solo tengan tooltip los botones,  y eso incluiria a los botones de carga y descarga de ficheros

**Comment by alvarag** [comment]
Toda la info que creo que faltaba y/o podías necesitar:

```
Parametros	Definición (Unidades) [Interacción con los objetivos]
ExiCap		Capacidad existente en cada nodo (MW)
CapAva		Capacidad instalable en cada nodo (MW)
GenAva		Generacion renovable en cada nodo (%)
Dem			Demanda en cada nodo en cada franja horaria (MW)
Hours		Horas en cada franja horaria (h)
Tem			Temperatura horaria en cada region (ºC)
L    			Tipo de linea
Dis 			Distancia entre nodos (km)
DemFor		Margen de reserva por error en el pronostico de demanda (%)
RenFor		Margen de reserva por error en el pronostico de generación renovable (%)
Cap 			Capacidad de las nuevas plantas por tecnologia (MW)
NewCapCos	Coste de inversión de nuevas plantas de generación ($/MW)		[Coste de inversion]
ManCos 		Coste de mantenimiento de las plantas de generación ($/MW)		[Coste de mantenimiento]
GenCos 		Coste de operación de las plantas de generación	($/MWh)			[Coste de operación]
Lifetime		Vida util de las plantas de generación (Años)
GHGEmi		Emisiones de Gases de Efecto Invernadero (TonsCo2eq)		                [Emisiones]
InvCapEmp	Empleo en la construccion de las plantas de generación		        	[Empleo en construcción de plantas]
ManCapEmp	Empleo en el mantenimiento de las plantas de generación			        [Empleo en mantenimiento de las plantas]
DecCapEmp	Empleo en el desmantelamiento de plantas de generación		         	[Empleo en desmantelameinto de plantas]
O&MCapEmp 	Empleo en la operación de plantas de generación					   [Empleo en operación/generación]
FueCapEmp	Empleo en la producción, procesamiento y transporte de combustibles [Empleo en combustibles]
WatCon		Consumo de agua para la generación de Energía [Consumo de agua]
WatWit 		Retiro de agua para la generación de energia [Retiro de agua]
FueCon 		Consumo de combustible por tecnologia de generación			
GENCOPri 	Precio de venta de energía de las compañias generadoras			
FueCos		Precio del combustible 										
FueNat 		Producción nacional de combustible
```

**Comment by fransaiz95** [comment]
Muchas gracias Alvar. Me falta el campo "power" de la tabla fuels_technologies, yo no se si lo más correcto es quitarlo pues no figura en ninguna de estas documentaciones.

Lo de los tooltips lo vemos mañana en la reunión.

**Comment by alvarag** [comment]
¿Desde qué pantalla se mantiene dicho campo?

**Comment by fransaiz95** [comment]
desde aquí: [fuels-technologies](https://www.proyectoubu.nesiweb.com/fuels-technologies/edit/1/9)

**Comment by alvarag** [comment]
¿Y de dónde viene ese campo? Porque igual nos lo hemos inventado... :S

**Comment by fransaiz95** [comment]
Pues me lo habré inventado si, lo habré confundido con el "power" de regions-technologies.
Lo elimino, ningún problema.

**Comment by alvarag** [comment]
Perfecto, un campo menos ;)

**Comment by fransaiz95** [comment]
Buenas noches, he actualizado los anexos:
He añadido un nuevo requisito con su caso de uso y su diagrama de casos de uso.
He añadido tambien el diccionario de datos con todos los campos de cada entidad explicados.

Mañana repasamos las cosillas que faltan, que no me ha dado tiempo a más.

Un saludo.

**Comment by jmaudes** [comment]
Incluyo revision diccionario
Los casos de uso nuevos no comento nada porque me parecen OK
[anexos (4 feb revision diccionario).pdf](https://github.com/fransaiz95/Weblectric2018/files/2828871/anexos.4.feb.revision.diccionario.pdf)

**Comment by fransaiz95** [comment]
Buenas tardes, podría ser esta una de las dos versiones que dijimos del diagrama entidad relación?

![entidad-relacion](https://user-images.githubusercontent.com/33490785/52278490-7565a500-2957-11e9-8b8c-4b3434617c04.png)

**Comment by fransaiz95** [comment]
faltaría convertir la de región y arcos en lo que dijimos.

**Comment by jmaudes** [comment]
Eso es!, como dice Alvar falta la version en la que los arcos son a la vez una reflexiva N:N y una agregacion que se relaciona N:N con tipo de linea

Pero en lo concerniente a esta version que has colgado hay bastantes cosas que comentar, muchas de las mismas me hacen pensar que estoy regalando los aprobados en bases de datos :

1) En region el atributo name no esta en el diccionario

2) En el diagrama E/R nunca se ponen las claves ajenas, si hubieramos usado el diagrama E/R con un SGBD no-relacional las FKs no hubieran llegado a existir. En ese sentido:
--En arcos quitar id_region_1 e id_region_2
--En RangeMeteo quitar id_region
--En RageDemand quitar tb id_region
--En Rangerenewables veo 3 claves (3 atributos subrayados). Eso es imposible en el E/R ...

[ Recuerda: En el diagrama E/R solo se representa una clave aunque haya varias (si hay mas claves se pueden hacer comentarios al diagrama). Recuerda tb que las claves compuestas se representan por racimos, como atributos compuestos]

Pero en este caso me temo que es otro problema: lo que quieres representar es la tabla que sale de la ternaria y que tiene la clave compuesta por los 3 atributos. Esa clave esta compuesta por 3 claves ajenas que por ser ajenas tampoco se representan. Entonces, la entidad Rangerenewables solo tiene los atributos start y end; los otros atributos salen al representar la ternaria como una tabla, y al eliminar la tabla de la entidad Rangerenewables porque hemos visto que no aporta nada. Por ello:

--Quita la clave ajena idTechnology
--Quita la clave ajena idRegion
Y te quedas con idStart como clave de Rangerenewables 

Entiendo que a todo este lio ha contribuido bastante el haber llamado a la entidad "Rangerenewables" y a la tabla que representa la ternaria tb "Rangerenewables", que me parece bien, pero siempre que tengamos claro que la tabla Rangerenewables no es la que representa la entidad, sino la que representa la ternaria. La tabla que representa la entidad la hemos suprimido al pasarlo a tablas y simplificar.

3) Si encierras un atributo en una linea discontinua, no estas indicando que es un discriminante de la debil, estas indicando otra cosa (que es un campo calculado... ) Los discriminantes se representan en una burbuja continua, pero subrayados con lineas discontinuas en lugar de continuas.
Debes de cambiar
-- start en rangemeteos
-- start en rangedemand

Una bobada final:
En el diccionario de datos las entidades estan en plural, y en el diagrma estan en singular. No se si merece la pena arreglarlo

**Comment by fransaiz95** [comment]
Buenas noches. Muchas gracias Jesús por la aclaración. Ahora creo que lo he entendido mejor.

A falta de crear la segunda versión del diagrama entidad-relación, creo que los anexos B, C y D podrían estar completos. Por si me los podeis revisar.

Me quedaría el anexo E.

Un saludo.

**Comment by alvarag** [comment]
¿Están subidos? Veo que la última actualización de los anexos es de 5 días atrás

**Comment by fransaiz95** [comment]
Pues entonces se me habrá olvidado hacer el commit ayer por la noche...
Cuando llegue a casa lo subo.

El 8 feb. 2019 9:55, Álvar Arnaiz-González <notifications@github.com> escribió:

¿Están subidos? Veo que la última actualización de los anexos es de 5 días atrás

**Comment by fransaiz95** [comment]
> ¿Están subidos? Veo que la última actualización de los anexos es de 5 días atrás

Commit hecho, perdonad.

Muchas gracias!

**Comment by fransaiz95** [comment]
He incluido la segunda versión del diagrama entidad-relación, la dejo aquí por si no esta bien modelado:

![diagramaer2](https://user-images.githubusercontent.com/33490785/52489180-e01a1900-2bc1-11e9-9972-02b46baaa32a.png)

**Comment by jmaudes** [comment]
A falta de una comprobación campo a campo para ver si concuerda con el diccionario y con el otro diagrama, parece que esta bien salvo por el detalle de que los discriminantes **_start_** en las e. débiles están con subrayado continuo en lugar de subrayados discontinuos, con lo cual parecen claves en lugar de discriminantes. Ya que estamos lo hacemos bien del todo no?

**Comment by fransaiz95** [comment]
Efectivamente Jesús, se me había olvidado cambiarlo tambien aquí. 
Lo dejo subido en el último commit para que los anexos tengan ya esta versión.

**Comment by jmaudes** [comment]
Hola
Ahi dejo las revisiones de los anexos B,C y D
[anexos(9-Feb anexosBCD).pdf](https://github.com/fransaiz95/Weblectric2018/files/2848245/anexos.9-Feb.anexosBCD.pdf)

Saludos
Jesus
