### ISSUE TITLE
Problema al mantener arcos

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#55]
Cuando trato de editar un arco:

![imagen](https://user-images.githubusercontent.com/9881614/51545650-b099ab80-1e62-11e9-9404-8063d110c9e4.png)

Al pulsar sobre el lapicero:

![imagen](https://user-images.githubusercontent.com/9881614/51545685-c6a76c00-1e62-11e9-9fe1-671fc4b0a911.png)

**Comment by fransaiz95** [comment]
Corregido.

**Comment by alvarag** [comment]
Perfecto, veo que no se puede cambiar el número de líneas en el alta ¿algún motivo en especial?

![imagen](https://user-images.githubusercontent.com/9881614/51667798-0b491980-1fc1-11e9-96c1-48dbe94814cf.png)

**Comment by fransaiz95** [comment]
No se puede cambiar hasta que selecciones el tipo de linea pues sino es posible que se intentase generar un numero de lineas sin especificar de que linea. Si seleccionas un tipo de linea, ya podrás decir cuantas lineas quieres.

**Comment by alvarag** [comment]
De acuerdo, no me había dado cuenta de ello. Gracias

**Comment by alvarag** [comment]
Una pregunta adicional, supongo que es problema de los datos del cliente, pero no le veo mucho sentido.

![imagen](https://user-images.githubusercontent.com/9881614/51668218-08025d80-1fc2-11e9-9fa3-6b2024151ca0.png)

Todo arco debería tener un tipo de línea(capacidad) y número de líneas, ¿no?

**Comment by alvarag** [comment]
Prometo que esto es lo último ya... pero creo que deberíamos modificar en vez de insertar en el caso de que el arco nuevo tenga los mismos datos que otro arco existente.
Ejemplo: tenemos de Hermosilla a Mulegé un arco de 100MW y al crear uno nuevo sería mejor (entiendo) que hiciera un update del número de líneas que no que genere dos.
Si se me escapa algo me lo decís.

![imagen](https://user-images.githubusercontent.com/9881614/51668475-92e35800-1fc2-11e9-8e83-bc416e845186.png)

**Comment by fransaiz95** [comment]
> Todo arco debería tener un tipo de línea(capacidad) y número de líneas, ¿no?

Pues debería si, luego miro a ver en el excel que nos pasaron si es problema de cómo nos pasaron los datos o de que los he cargado mal.

De hecho, puede haber 2 arcos:
- Madrid - Burgos con distancia 250km por la A1
- Madrid - Burgos con distancia 285km por la A1* mas nacional un trozo (por poner un ejemplo)

Me faltaría comprobar el caso que tu dices si, en caso de meter los mismos datos (id_region1, id-region2 y tipeline_id) que lo actualice a los nuevos valores.

**Comment by jmaudes** [comment]
Una bobada que tiene que ver con esta discusión
Cuando doy de alta un arco, me vuelve a la pantalla de Tecnologies
Es intencionado?

**Comment by alvarag** [comment]
Creo que se debería añadir una restricción para no poder crear arcos de un país a otro.

![imagen](https://user-images.githubusercontent.com/9881614/52421064-982cc080-2af3-11e9-8d54-1e86162397f9.png)


Otra cosa, no sé si hay alguna dependencia que no caigo, pero ¿por qué no me deja borrar un arco?

![imagen](https://user-images.githubusercontent.com/9881614/52421188-d924d500-2af3-11e9-8b4b-b554361959ae.png)


Por último, es un detalle pero no cuesta mejorarlo: que no deje añadir un combustible a una tecnología renovable. Que en ese desplegable aparezcan solamente las energías "sucias".

![imagen](https://user-images.githubusercontent.com/9881614/52422094-ae3b8080-2af5-11e9-90f9-d4fb5c890d56.png)

Nota: recuerda ir cerrando issues, yo creo que hay algunas que ya están completadas pero siguen abiertas.

**Comment by fransaiz95** [comment]
Genial. Gracias por los apuntes Álvar. Ya están corregidos. 
En cuanto el tema de borrar el arco, daba error de que estaba relacionado con un tipo de linea, pero en este caso, tendría que eliminar esa relación tambien y ya está.
