### ISSUE TITLE
Cambios estéticos de la interfaz

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#56]
Los cambios que me ha indicado el usuario son los siguientes:

- [Pantalla Regions](https://www.proyectoubu.nesiweb.com/countries/view/1): quitar DemFor y RenFor

- [Pantalla Climate](https://www.proyectoubu.nesiweb.com/rangemeteos/home): selector de años y para cada año se puede introducir una nueva hoja de cálculo.

- [Pantalla Technologies](https://www.proyectoubu.nesiweb.com/technologies/home): dentro de visualizar o de modificar, que aparezcan los campos con la unidad correspondiente (MW, $/MW...), que aparezcan separadores de miles y millares, etc. Además, que haya una pequeña ayuda en cada campo (al pasar por encima, con información - que nos tienen que pasar).

- [Types of Lines](https://www.proyectoubu.nesiweb.com/typelines/home): Eff lin debería ser Voltage. Y tanto al editar como al visualizar que aparezca Voltage en vez de Tension.

- [Pantalla Fuels](https://www.proyectoubu.nesiweb.com/fuels/home): Quitar Production  de la pantalla principal (ya que depende del país la producción).

**Comment by fransaiz95** [comment]
> Pantalla Regions: quitar DemFor y RenFor

De todos los sitios? Solo de la tabla? De la administración tambien?
   
> Pantalla Climate: selector de años y para cada año se puede introducir una nueva hoja de cálculo.

Entendido

> Pantalla Technologies: dentro de visualizar o de modificar, que aparezcan los campos con la unidad correspondiente (MW, $/MW...), que aparezcan separadores de miles y millares, etc. Además, que haya una pequeña ayuda en cada campo (al pasar por encima, con información - que nos tienen que pasar).

Entendido, espero a que nos pasen esa información.

> Types of Lines: Eff lin debería ser Voltage. Y tanto al editar como al visualizar que aparezca Voltage en vez de Tension.
 
Entendido

> Pantalla Fuels: Quitar Production de la pantalla principal (ya que depende del país la producción).

La misma duda, solo de la tabla donde se listan, o tambien de las administraciones?

**Comment by alvarag** [comment]
Quitar Production, DemFor y RenFor solamente de la pantalla de resumen: tiene que seguir pudiéndose mantener y estar en las tablas.

**Comment by alvarag** [comment]
Los objetivos mejor hacia abajo en listado uno detrás de otro: es como lo quería el usuario.

**Comment by fransaiz95** [comment]
Correcto.

**Comment by fransaiz95** [comment]
Dejo estas tareas en checkbox y voy marcándolas, si hay alguna que no está como se desea me lo indicas y la desmarcais porfavor.

- [x] Pantalla Regions: quitar DemFor y RenFor
- [x] Pantalla Climate: selector de años y para cada año se puede introducir una nueva hoja de cálculo.
- [x] Pantalla Technologies: dentro de visualizar o de modificar, que aparezcan los campos con la unidad correspondiente (MW, $/MW...), que aparezcan separadores de miles y millares, etc. Además, que haya una pequeña ayuda en cada campo (al pasar por encima, con información - que nos tienen que pasar).
- [x] Types of Lines: Eff lin debería ser Voltage. Y tanto al editar como al visualizar que aparezca Voltage en vez de Tension.
- [x] Pantalla Fuels: Quitar Production de la pantalla principal (ya que depende del país la producción).

**Comment by fransaiz95** [comment]
Añadido desplegable para seleccionar los años en la importacion y exortación de datos.
En la importación, se borrará todo lo que hay actualmente en bd correspondiente a ese año
En la exportación, aparecerá un mensaje en la alerta dependiendo del número de registros. Te descargaras los correspondientes a ese año.
