### ISSUE TITLE
Deja insertar 2 tipos de arcos con igual capacidad y Eff-in

### ISSUE THREAD

**Issue by jmaudes** [fransaiz95/Weblectric2018#57]
Al insertar 2 arcos repitiendo los 2 valores (Line cap y Eff in) no portesta, sin embargo según el diagrama relacional de la especificación de diseño, ambos campos parecen conformar una clave primaria compuesta

**Comment by fransaiz95** [comment]
Buenas Jesús, te refieres a Tipos de linea verdad? (Typelines). No se que es lo que te hace llegar a la conclusión de que "según el diagrama relacional de la especificación de diseño, ambos campos parecen conformar una clave primaria compuesta", puede ser que algo haya puesto mal en el diagrama, pero los tipos de linea tienen su propia primary key simple. 

Me dices, creo que algo no he entendido bien.

**Comment by jmaudes** [comment]
Perdona, he confundido la tabla typeLine con arc_TypeLine
Cierra el issue
