### ISSUE TITLE
Administración de usuarios.

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#58]

**Comment by fransaiz95** [comment]
Buenas noches. Me he lanzado a la piscina y me he puesto con la administración de usuarios.

Ahora, nada mas acceder, pide autentificación.

Se han añadido 2 tablas nuevas:

- roles: id(int) + name(varchar)
- users: id(int) + username(varchar) + password(varchar) + name(varchar) + surname(varchar)

Ahora, por si quereis acceder, hay dos usuarios creados:
- Rol administrador: 
  - login: admin
  - password: admin
- Rol usuario: 
  - login: user
  - password: user

Falta meter la administración de usuarios, que el administrador pueda crear y asignar roles y que el rol usuario no pueda hacer nada mas que cambiar sus propios datos (sin el rol claro).
Falta poner bien el logout... que ahora está ahi tirado en la cabecera... Faltan varias cosillas, no obstante me decís lo que vais viendo.

Deduzco que esto requerirá de varios cambios...
Por lo menos, actualizar los diagramas, que así aprovecho para hacer las aclaraciones que dijimos.

¿Tenéis en mente alguna cosa que tendría que cambiar? ¿De las que dijimos el otro día?

PD: Ahora mismo están bloqueadas todas las urls antes de loguearse menos una: [Add new user](https://www.proyectoubu.nesiweb.com/users/add) para que creeis algún usuario.

Al resetear la base de datos volveran a quedar los 2 iniciales.

**Comment by alvarag** [comment]
¡Perfecto! Ve rematando estos flecos que sino luego da la sensación de "poco serio" el desarrollo

**Comment by fransaiz95** [comment]
Buenas noches, os cuento como ha quedado este modulo.

He recogido en un submenú de la cabecera las nuevas acciones propias de la gestión del usuario.

Dos posibles roles para los usuarios: (Podemos cambiar facil el nombre si no es correcto)
- Administrador
- Usuario

**Usuario administrador:**
- Tendrá acceso a una administración de todos los usuaios. Podrá crear/editar/delete. 
- Destacar que a él mismo no se podrá borrar, así evitaremos que la aplicación se quede sin usuarios.
- Tiene acceso a poder restablecer la base de datos.

**Usuario de rol usuario:**
- No tendrá acceso a ninguna de las pantallas istadas para los administradores. Si se intenta acceder por url, será redirigido automáticamente a la pantalla principal.
- Podra editar los datos solo de su propio usuario desde la pestaña "my data" de la cabecera. No se podrá cambiar el rol. Esta funcionalidad queda solo para el administrador.

Me comentais las dudas y si hay alguna mejora. Creo que este modulo aporta bastante valor y funcionalidad a la aplicación.

**Comment by jmaudes** [comment]
En cuanto a la funcionalidad perfecto, me gusta como ha quedado
Al probarlo dandome de alta como otro administrador me da el siguiente error

![error insert user](https://user-images.githubusercontent.com/1501818/51733686-62fb8980-2082-11e9-9f1d-98dec3d1d687.PNG)

Jesus

**Comment by fransaiz95** [comment]
Efectivamente, es porque tiene el selector de roles deshabilitado y al estar deshabilitado no se manda el valor. Debería no estar deshabilitado para poder seleccionar el rol correspondiente, se me habrá escapado alguna condición.

Lo corrijo.

**Comment by alvarag** [comment]
¿Lo actualizaste? A mí no me ha dejado meter un nuevo administrador.

![imagen](https://user-images.githubusercontent.com/9881614/51993922-0946f500-24b0-11e9-81e1-bc2ba93e49ec.png)

**Comment by alvarag** [comment]
Además no me deja cambiar el rol, así que no he podido probar el mto de usuarios

Al editar tampoco me deja cambiar el rol...

**Comment by fransaiz95** [comment]
Buenas tardes... se me había olvidado hacerlo si, gracias por recordarlo.

Ya está subido.

> Al editar tampoco me deja cambiar el rol...

Ahora mismo deja editar el rol siempre y cuando el usuario logueado sea administrador.
Si se loguea como participante, no podrá cambiarse de rol a si mismo.
