### ISSUE TITLE
Cancel Energías renovables no vuelve donde debería

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#59]
He detectado que el botón de Cancel de "Renewable Energies" no vuelve a donde debería:

![imagen](https://user-images.githubusercontent.com/9881614/51734667-8247e600-2085-11e9-8db3-354fa49420f0.png)

Tras cancel se va a Climate:

![imagen](https://user-images.githubusercontent.com/9881614/51734687-8f64d500-2085-11e9-8fe6-a7f911584d3d.png)

**Comment by alvarag** [comment]
Me he dado cuenta de chiripa, pero ahí se ve cómo no está funcionando bien el responsive de la cabecera y migas de pan:

![imagen](https://user-images.githubusercontent.com/9881614/51734770-c4712780-2085-11e9-9953-55fc0948462e.png)

**Comment by fransaiz95** [comment]
Es verdad... Se ve roto... Lo daré una vuelta a ver

**Comment by fransaiz95** [comment]
A falta de mirar el responsive, está corregido.
