### ISSUE TITLE
Tareas asíncronas PHP

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#61]

**Comment by fransaiz95** [comment]
Buenos días, he estado mirando y buscando como realizar con PHP peticiones asíncronas y PHP no está preparado para ello.

Se me ha ocurrido una solución, no se como de válida será, os la comento:

Puedo realizar el proceso en segundo plano a través de una tarea programada que se ejecute en el servidor cada X tiempo.

El flujo sería:

- Cuando hago click en el botón de simulación, guardaría en una tabla nueva en base de datos un nuevo registro con información para la tarea programada.
- Tendría una tarea programada que consultaría cada X tiempo (1-2 min por ejemplo) si en esa tabla hay registros sin procesar. De ser así, se bloquearía la escritura en esa tabla para que no se lanzasen más peticiones y se ejecutaría una función que realizaría las cosultas y generase el zip.
- Se escribiría a completado la tarea en la tabla de la base de datos y se notificaría a través del email.

No se si es buena idea o no, así es como en el trabajo enviamos los email pendientes, con una tarea programada que se ejecuta cada X tiempo y comprueba de la tabla emails aquellos que están sin enviar.

Me comentáis que opinais, o si es mucho jaleo pues... lo dejamos.

Un saludo.

**Comment by jmaudes** [comment]
No puedes declarar un trigger en la tabla AFTER INSERT ROW que llame a un modulo (p.e. un proc almacenado de MySQL) que ejecute la tarea?

http://ftp.nchu.edu.tw/MySQL/doc/refman/5.0/en/create-trigger.html
https://stackoverflow.com/questions/1467369/invoking-a-php-script-from-a-mysql-trigger

A priori, parece que si, no es largo de hacer y si daria valor añadido

No se si os convence

Jesus

El jue., 31 ene. 2019 a las 11:26, fransaiz95 (<notifications@github.com<mailto:notifications@github.com>>) escribió:

Buenos días, he estado mirando y buscando como realizar con PHP peticiones asíncronas y PHP no está preparado para ello.

Se me ha ocurrido una solución, no se como de válida será, os la comento:

Puedo realizar el proceso en segundo plano a través de una tarea programada que se ejecute en el servidor cada X tiempo.

El flujo sería:

  *   Cuando hago click en el botón de simulación, guardaría en una tabla nueva en base de datos un nuevo registro con información para la tarea programada.
  *   Tendría una tarea programada que consultaría cada X tiempo (1-2 min por ejemplo) si en esa tabla hay registros sin procesar. De ser así, se bloquearía la escritura en esa tabla para que no se lanzasen más peticiones y se ejecutaría una función que realizaría las cosultas y generase el zip.
  *   Se escribiría a completado la tarea en la tabla de la base de datos y se notificaría a través del email.

No se si es buena idea o no, así es como en el trabajo enviamos los email pendientes, con una tarea programada que se ejecuta cada X tiempo y comprueba de la tabla emails aquellos que están sin enviar.

Me comentáis que opinais, o si es mucho jaleo pues... lo dejamos.

Un saludo.

**Comment by alvarag** [comment]
Hoy intentando entender el código en R que optimiza y realiza los cálculos, veo que en cuanto a datos no son muchos los que debería bajarse, por lo que igual el generar "al vuelo" los registros en csv y comprimrilo en zip podría ser la opción más sencilla para poder dar carpetazo al proyecto.

**Comment by fransaiz95** [comment]
Pues si puedo hacerlo de esta manera que comentas Alvar, sería muchísimo mejor y asi cerramos.

Lo que no se es de todos los archivos que hay en el zip, los que yo tengo que generar.

**Comment by alvarag** [comment]
La idea sería generar todos los ficheros (o los que podamos) de los que ellos tienen en la carpeta Parametros.

Básicamente sería sacar la información de todas las tablas menos las de consumos y generación (creo). Revisa el documento que te envié con la información de cada fichero y revisas si te cuadra

**Comment by fransaiz95** [comment]
Buenas Alvar, una duda acerca de los archivos a exportar:

El fichero Hours.txt, tiene 15 columnas, y cada valor es el número de horas en un año. Siendo 8760 horas las de un año de 365 días y 8784 las horas de un año bisiesto.

Sabes por qué 15 filas? Será porque tienen un histórico ya de 15 años?

**Comment by alvarag** [comment]
Sí, creo que ese es exactamente el motivo. Lo que no sé es si es un resumen (media) de los datos que hay en la otra carpeta (la de demanda).

**Comment by fransaiz95** [comment]
Buenas tardes. Podeis entrar en el apartado de [_simulation->downloads_](https://www.proyectoubu.nesiweb.com/simulations/home) a ver lo que sería un primer funcionamiento de toda esta parte.
En el zip que descargais, veis los archivos que hasta ahora he podido preparar, me faltan un par de ellos todavía.

No obstante, de esta manera va rápido y parece que puede ser buena solución verdad?

Lo he gestionado de la siguiente manera: Cada simulación va asociada a un usuario, de tal manera que cada usuario solo ve las suyas. Os parece bien??

Un saludo, ya me decís.

**Comment by fransaiz95** [comment]
Buenos días. 
Relacionado con esto. De los datos presentes en el archivo TypLin, solo tengo el dato: LinCap. 
El resto o se refieren a otra cosa de las que nosotros tenemos o son datos que no tenemos. 

Muchas gracias. Si nosotros no sabemos la respuesta, podríamos preguntar al cliente a ver?

Un saludo.

**Comment by alvarag** [comment]
Esta tarde recuérdame este tema porque ya no tengo claro qué es qué.

En cuanto a las simulaciones todo bien y perfecto. Lo único, habría que descargar también el individuo.R para que corra la simulación

**Comment by fransaiz95** [comment]
Esta tarde lo miramos si.

**Comment by fransaiz95** [comment]
Buenas noches. 

Creo tener la aplicación al completo.
Podeis echar un ojo a la simulacion y a la estructura de ficheros que devuelve y a los cambios que comentamos el otro día. A partir de mañana, me pondré con la documentación y la corrección de pequeños fallos que veamos.

Un saludo.
