### ISSUE TITLE
Pequeña reestructuración de países

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#62]
Probando la aplicación y metiendo un nuevo país, me he dado cuenta de que el cliente no tiene claro cómo quiere que se comporte. Ahora mismo, entras en "Countries Data", y aparecen datos como la demanda, clima y renovables que son dependientes del país.

No sé si esto supondría muchos cambios, en cuyo caso podría dejarse como mejora futura:

- Al pulsar en Countries Data ir directamente a la pantalla: https://www.proyectoubu.nesiweb.com/countries/home
- Y al pulsar sobre el ["ojo" en un país](https://www.proyectoubu.nesiweb.com/countries/view/2), que vayas a una pantalla como la que hay ahora al dar a Countries Data.
- Pero en vez de "Country" "Renewable ..." "Climate" y "Demand", que fueran: "Regions", "Renewable ...", Climate y Demand.

De este modo, todos los elementos del país, estarían tras haber seleccionado el país.

Y así luego tanto la demanda como el clima como las renovables, te descargaría la tabla excel con las regiones de dicho país y no de todos los de la BBDD.

¿Me he explicado bien? ¿Crees que lleva mucho desarrollo?

**Comment by fransaiz95** [comment]
Entiendo lo que dices y el por qué te ha llevado ahí si.
Voy a ver como voy de tiempo a lo largo del fin de semana y si me da tiempo lo cambio, que si que estaría mejor en el caso en que añadan un nuevo país a la instalación.

**Comment by fransaiz95** [comment]
Se dejará para líneas futuras del proyecto.
