### ISSUE TITLE
Error si no se selecciona fichero

### ISSUE THREAD

**Issue by alvarag** [fransaiz95/Weblectric2018#63]
Si no seleccionan/cargan ningún fichero y le dan a save: falla.

![imagen](https://user-images.githubusercontent.com/9881614/52467759-e6d76a80-2b86-11e9-8fdc-c8b7a7768a2d.png)

**Comment by fransaiz95** [comment]
Corregido. Se ha puesto un mensaje de satisfacción y de error en todas las pantallas. Igual en el login cuando era incorrecto, al editar o crear un nuevo elemento... etc.
