### ISSUE TITLE
Anexo E: Manual del usuario

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#64]

**Comment by fransaiz95** [comment]
Buenas noches.

He corregido las siguientes cosas quye me comentó Jesús.
Excepciones en tabla "Caso de uso 1 Administracion mediante formularios"
Excepciones en tabls "Caso de uso 2 Administración mediante hojas de cálculo."
Excepciones en tabla "Caso de uso 4 Exportar datos en hoja de cálculo"
Precondiciones en tabla "Caso de uso 5 Restablecer la base de datos"
Excepciones en tabla "Caso de uso 6 Administración de usuarios"
Precondiciones y excepciones en tabla "Caso de uso 7 Simulación y descarga de ficheros generados"

Con esto, podríamos dejar cerrados los anexos A, B, C y D.

He escito ya el anexo "E: Manual del usuario" y el resumen/abstract, por si me lo podeis revisar.

Me quedarían ya solo de la memoria: 

- conclusiones y lineas futuras.

**Comment by fransaiz95** [comment]
Alvar, por si me puedes ayudar con un problema de representar ilustraciones:

- debajo de una descripcón que dice... "descomentar la siguiente linea" pongo con latex un codigo fuente y entre el texto y esa linea de comandos, me introduce una imagen quedando desplazado el texto de la referencia al código. Se puede hacer algo para que entre medias, latex no me ponga la imagen?

**Comment by fransaiz95** [comment]
Nos podemos ver mañana lunes por la tarde? Para comentar últimas cosillas y dejarlo cerrado? Sino martes por la tarde antes de ir a imprimir.

Muchas gracias y un saludo.

**Comment by alvarag** [comment]
> Alvar, por si me puedes ayudar con un problema de representar ilustraciones:
> 
>     * debajo de una descripcón que dice... "descomentar la siguiente linea" pongo con latex un codigo fuente y entre el texto y esa linea de comandos, me introduce una imagen quedando desplazado el texto de la referencia al código. Se puede hacer algo para que entre medias, latex no me ponga la imagen?

Si el problema es que LaTeX te coloca las imágenes/ilustraciones donde él quiere: no te preocupes, él sabe mejor que nosotros donde queda bien y dónde no queda bien la imagen.

No obstante, si quieres forzar una imagen a que aparezca en un sitio concreto lo puedes hacer con el argumento [h!] del comando figure.

Tengo las tardes de hoy y mañana hasta arriba, ¿podría ser el miércoles?

**Comment by fransaiz95** [comment]
Vale, gracias por lo de LaTeX.

En cuanto a la reunión, lo malo del quedar el miércoles es que me gustaría haberlo dejado cerrado ya todo para el miércoles ir a imprimirlo, pues hay que entregar el jueves.
Si no hay que comentar nada más y puedo dejar cerrado la documentación y anexos ya del todo, podríamos quedar el miércoles para ver lo del cartel y esos otros temas. Lo que veáis vosotros.

No obstante, si habiendo corregido la documentación consideráis que es conveniente vernos y tiene que ser por la mañana porque el lunes o martes por la tarde no podéis, me podría escapar un rato del trabajo para comentarlo.

**Comment by alvarag** [comment]
Revisados los anexos y apuntados algunos comentarios menores.

[anexosC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2850223/anexosC.pdf)

Sino quedad sin mi, para no pillarte los dedos con los plazos

**Comment by fransaiz95** [comment]
Gracias por las aclaraciones, esta tarde lo corrijo y hago las conclusiones.

En cuanto a la reunión, como prefiráis.

**Comment by jmaudes** [comment]
Hola

Veo que Alvar ha revisado el anexo que quedaba. Si queda algo mas por revisar dime, que ya he vuelto a la vida después de un mes de Enero de aupa. 

En cuanto a quedar, yo también prefiero el miércoles, pero por poder venir, puedo hacer una escapada de un rato a la hora que digas tanto hoy como mañana martes.

De todas formas, si puedes adelantar a lo largo de la mañana las dudas que quieres cerrar, las comento con Alvar, por si hay alguna que necesite el consenso de los 2 tutores

Jesus

**Comment by fransaiz95** [comment]
> De todas formas, si puedes adelantar a lo largo de la mañana las dudas que quieres cerrar, las comento con Alvar, por si hay alguna que necesite el consenso de los 2 tutores

Nada, no tengo dudas concretas. En cuanto a la aplicación, creo que no me da tiempo a hacer las últimas sugerencias que comentaba Álvar, y no quiero ponerlo patas arriba a todos los flujos, pues son horas y luego dejarlo roto. Por lo que había pensado meterlo en el apartado de líneas futuras.

Lo que quería cerrar es la memoria y anexos, yo creo que a falta de las conclusiones, está todo cerrado, pero era por echarlo un ojo juntos y dar el visto bueno general, nada más. Si juntos o cada uno por separado lo echa un ojo y da el visto bueno, no haría falta reunirnos. Hoy cambio los últimos aportes y sugerencias y mañana y el miércoles prepararía la entrega.

**Comment by jmaudes** [comment]
OK
Entonces, salvo que me digas lo contrario por este mismo canal antes de las 17:00, entiendo que esta tarde no vas a venir y que en consecuencia yo no tengo q venir

En cuanto a las mejoras sugeridas por Alvar, pues si, es mejor presentar una version estable; pero para eso Git es un sistema de control de versiones. Lo suyo es crear una rama y ver hasta donde te da tiempo arreglar y hacer el merge si al final te da tiempo (y muy importante, lo tienes BIEN probado). Eso no se como lo podemos reflejar en documentacion por si el merge se demora mas alla de esta semana. Que te de Alvar su opinion que yo le voy a apoyar sea cual sea.

**Comment by alvarag** [comment]
Estoy de acuerdo con Jesús. Una cosa que sí hay que tener bien claro es qué queremos que se descargue en el zip y cómo se ejecutaría:

 - Dijimos de descargar un zip con tres carpetas:
    - Codigo: el código en R con el algoritmo. Recuerda que tenía "ñ" en el código y había que cambiarlas para que no fallara.
    - Data: los datos y parámetros de nuestra BBDD. Además del json, los ficheros en txt que contienen la información de nuestra aplicación.
    - Parametros: ficheros ".txt" que nos suministró el cliente y que hace que funcione para su código.

 - En el anexo del usuario hay que explicar esto bien y decir cómo se puede ejecutar el algoritmo de optimización: `Rscript individuo.R` (dentro de la carpeta Codigo)
 - Indicar que hay que tener R instalado si quieren ejecutar la simulación.

**Comment by fransaiz95** [comment]
Buenas noches, debí de entender mal la estructura de la exportación, ya está corregido.
He corregido tambien los comentarios que me habeis hecho a los anexos y he incluido las cosas nuevas: La ejecución del algoritmo, el despliegue en el servidor...

Creo que con eso estarían los anexos cerrados.

Para mañana me quedaría solo la conclusión y las líneas futuras.
En líneas de desarrollo para el futuro, que elementos pongo? 

Muchas gracias!

**Comment by alvarag** [comment]
He revisado el manual de usuario con los últimos cambios.
[anexosC.pdf](https://github.com/fransaiz95/Weblectric2018/files/2854774/anexosC.pdf)

**Comment by jmaudes** [comment]
También le he dado un vistazo (muy por encima) y me parece OK
