### ISSUE TITLE
Preparar entrega.

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#67]

**Comment by fransaiz95** [comment]
Buenas tardes, 
tras leer y realizar las correcciones en la memoria y si os parece bien, podemos dar por  cerrado el tema. Durante la tarde de hoy prepararé todo para mañana imprimirlo y generar el cd para el jueves poder entregar.

Cómo teneis la tarde del jueves? Para poder juntarnos y hablar sobre el cartel y la presentación? Así lo puedo hacer tranquilo el fin de semana.

Un saludo y muchas grracias de nuevo. Esto llega a su fin!

**Comment by jmaudes** [comment]
En princio jueves tarde OK, a que hora? cuanto mas tarde mejor, lo mismo me tengo que acercar al dentista sin cita y a ver cuando me meten ...

**Comment by alvarag** [comment]
Yo tengo reunión a las 17:30, así que a partir de las 18:30 hasta las 20.00 cuando os vaya bien

**Comment by fransaiz95** [comment]
Pues teniendo en cuenta eso, lo que prefiráis Jesús, no sé cuánto de tarde necesitas quedar, yo estoy disponible

El 12 feb. 2019 20:00, Álvar Arnaiz-González <notifications@github.com> escribió:

Yo tengo reunión a las 17:30, así que a partir de las 18:30 hasta las 20.00 cuando os vaya bien

**Comment by fransaiz95** [comment]
Tengo una duda, hay especificado en algún sitio todas las cosas que hay que entregar? Y papeles que hay que hacer?

**Comment by alvarag** [comment]
En UBUVirtual hay una especie de FAQ con las preguntas frecuentes, echa un ojo

**Comment by jmaudes** [comment]
Mañana a las 19:00? Si no dice nadie lo contrario, lo dejamos a esa hora

**Comment by alvarag** [comment]
> Mañana a las 19:00? Si no dice nadie lo contrario, lo dejamos a esa hora

Hablábamos del jueves, ¿no? Aunque yo podría también mañana a esa hora

**Comment by fransaiz95** [comment]
Hablábamos del jueves si, aunque igual quedar mañana está bien también, voy a imprimir antes y así vemos si me falta algo que soy bastante desastre par esas cosas

**Comment by jmaudes** [comment]
No se en que dia vivo ... perdon
Venga mañana miercoles a las 19:00 al final, si vamos un día por delante es siempre mejor para tener margen con esos pequeños detalles que lo arruinan todo en el ultimo momento
Jesus

**Comment by fransaiz95** [comment]
Perfecto, pues mañana miércoles a las 19h

**Comment by fransaiz95** [comment]
De cara a qué introducir en el cd, que os parece si dejo lo siguiente?
- SaizGuemesFranciscoMemoria.pdf - Memoria
- SaizGuemesFranciscoAnexos.pdf - Anexos
- /Codigo
  - weblectric.7z - con el codigo del proyecto
- /Base de datos
  - weblectric.sql - con la base de datos
  - diagrama entidad relacion
  - diagrama relacional
- weblectric.png - logo weblectric

Echáis de menos algo? Quizá los documentos que nos pasó el cliente donde dejaba especificado cada cosa? O eso es solo para conocimiento nuestro.

En cuanto a la carátula, tengo mis dudas sobre como debe de ser el modelo. Os dejo adjuntas las dos y así me decís. No se si debe de tener el logo de la aplicación o no.

![caratulacd_sin_logo](https://user-images.githubusercontent.com/33490785/52674078-d296c300-2f22-11e9-98ba-b47de04711c3.png)

![caratulacd_weblectric](https://user-images.githubusercontent.com/33490785/52674087-d62a4a00-2f22-11e9-8239-9fc3dd9ca4f4.png)

Un saludo y mañana a las 19 nos vemos con todo el material impreso.

**Comment by alvarag** [comment]
El CD es correcto, tanto el primero como el segundo.

En cuanto al CD, yo creo que lo mejor es mantener la misma estructura que tiene el repositorio Git, ya que es lo que explicas en el manual del programador.
