### ISSUE TITLE
Crear Diagrama Relacional y crear las tablas en base de datos.

### ISSUE THREAD

**Issue by fransaiz95** [fransaiz95/Weblectric2018#9]

**Comment by fransaiz95** [comment]
Dejo adjunto el diagrama ER que veíamos en el Sprint anterior a falta de completarlo por lo menos con las PK:

![weblectric er](https://user-images.githubusercontent.com/33490785/46680706-e5eaf800-cbe9-11e8-8b40-510984e62b07.png)

**Comment by fransaiz95** [comment]
Algo así podría ser el diagrama relacional? 
Me decís con los fallos y sugerencias y lo voy completando.
No se si se me escapa alguna de las cosas que hablamos ayer.

![diagrama relacional](https://user-images.githubusercontent.com/33490785/46680520-94db0400-cbe9-11e8-8333-e3b4489a27d9.png)

**Comment by jmaudes** [comment]
Como ya he dicho en el issue del E/R, en rangeRenowable hay una clave idTecnology-idRegion-Start. Personalmente yo la pondría como PK, ya que la idea de usar la clave artificial rangeRenowable.id es más adecuada si hubiese otra tabla "T" con una FK apuntando a rangeRenowable (es decir, evitarías que T tuviera que importar los 3 campos idTecnology-idRegion-Start, y en su lugar solo importaría el Id). Pero como no es el caso, no veo que ganemos nada con el id, a no ser que intuyas que por alguna razón te va a facilitar las cosas en PHP

Con las entidades débiles pasa lo mismo; por ejemplo RangeMeteo es débil con discriminante start, luego la PK es idRegion+start. Si ponemos una clave artificial debeira ser porque existiera una tabla T con una FK apuntando a RangeMeteo donde quisieramos evitar llevar esos 2 campos (idRegion+start) y en su lugar llevar sólamente el RangeMeteo.Id; pero nuevamente no es el caso.

RangeDemand seria el mismo caso que RangeMeteo (creo que te faltan start y end en el diagrama)

En Arc necesitas 2 FKs que apunten a Región, por ejemplo OriginReg y regDestinationReg (de hecho si lo hubieramos modelado como reflexiva habría salido así de manera automática; en este caso al poner el "2" en la cardinalidad tenemos que "pensar" en qué significa ese 2 y llegar a esa misma solución igualmente. De hecho, hay una clave candidata OriginReg + regDestinationReg en Arc, pues ese arco con ese origen y ese destino sólo tiene que aparecer una vez en la tabla de arcos. Aquí si que puede haber argumentos en favor de la clave artificial Arc.Id, porque evitas llevarte a la tabla arc_typeLine el par OriginReg + regDestinationReg.

Recuerda que los arcos son bidireccionales (quizás llamarlos OriginReg y regDestinationReg no sea la mejor idea, pues los puntos que conectan son órigenes y destinos a la vez). Para evitar que se de de alta el arco Chiapas-MexicoDF y a la vez MexicoDF-Chiapas, no sólo tendrás que incluir el UNIQUE que reconozca que OriginReg + regDestinationReg es una clave candidata, sino que tendrás que meter un CHECK (OriginReg < regDestinationReg), por ejemplo, para que si Chiapas es menor que MexicoDF, no te deje meter MexicoDF-Chiapas

**Comment by fransaiz95** [comment]
He estado dandole una vuelta y esto podría ser el resultado:

![diagrama relacional](https://user-images.githubusercontent.com/33490785/46756762-7b5cb980-ccc8-11e8-8161-7a8cb209d3e3.png)

La tabla arc, he decidido llamar idRegion1 & idRegion2 por el tema de que no son origen y destino como bioen comentabais. 

De cara a la BD, convertireé esos campos en unique y haré el: 
`Check idRegion1 < idRegion2 `
para cubrir lo que decíamos.

Espero que así este bien y haya corregido los errores del resto de tablas.

**Comment by jmaudes** [comment]
Parece que esta bien a falta de algún despistillo en el que no haya caido
Asi que adelante :-) 
Jesus

**Comment by fransaiz95** [comment]
Perfecto, gracias! ;)
